/* Baza pytań quizu PKM II — poziom egzaminacyjny.
 * Zakres wg "Pytań kontrolnych" oraz wykładów (delta / PK).
 * {t: temat, q: treść, a: [4 odpowiedzi], c: indeks poprawnej (0-3), e: wyjaśnienie}
 * Odpowiedzi mają zbliżoną długość, a kolejność jest losowana — nie da się zgadywać „po najdłuższej".
 */
window.TOPICS = {
  gwint: {name: "Połączenia gwintowe", ico: "\uD83D\uDD29"},
  spaw:  {name: "Połączenia spawane",  ico: "\uD83D\uDD25"},
  sprz:  {name: "Sprzęgła",            ico: "\u2699\uFE0F"},
  ham:   {name: "Hamulce",             ico: "\uD83D\uDED1"},
  przek: {name: "Przekładnie zębate",  ico: "\uD83E\uDDB7"},
};

window.QUESTIONS = [
/* ===================== POŁĄCZENIA GWINTOWE ===================== */
{t:"gwint",q:"Rozkład obciążenia na poszczególne zwoje gwintu w połączeniu śrubowym jest:",
 a:["równomierny – każdy zwój przenosi identyczną część siły",
    "nierównomierny – najbardziej obciążony jest pierwszy zwój",
    "nierównomierny – najbardziej obciążony jest ostatni zwój",
    "całkowicie losowy i niezależny od sztywności elementów"],c:1,
 e:"Z powodu odkształceń śruby i nakrętki obciążenie zwojów jest nierównomierne — najwięcej przenosi pierwszy (dolny) zwój."},
{t:"gwint",q:"Wysokość nakrętki m wyznacza się z warunku wytrzymałościowego na:",
 a:["wyboczenie smukłego rdzenia śruby pod naciskiem",
    "zginanie trzpienia od nieprostopadłego oparcia",
    "naciski powierzchniowe zwojów, aby p ≤ p_dop",
    "rozciąganie osiowe pierścienia nakrętki"],c:2,
 e:"Wysokość nakrętki dobiera się tak, by naciski na zwojach nie przekroczyły dopuszczalnych: p = Q/Az ≤ p_dop."},
{t:"gwint",q:"Powierzchnię współpracy zwojów gwintu Az opisuje zależność:",
 a:["Az = π·(d² − D₁²)·i, dla całej długości gwintu",
    "Az = (π/4)·(d² − D₁²)·i, gdzie i to liczba zwojów",
    "Az = (π/2)·(d + D₁)·i, jako pole boczne walca",
    "Az = π·d·i, jako pobocznica rdzenia śruby"],c:1,
 e:"Powierzchnia nośna zwojów Az = (π/4)(d² − D₁²)·i, gdzie i jest liczbą czynnych zwojów nakrętki."},
{t:"gwint",q:"Liczba czynnych zwojów gwintu nakrętki i wynosi:",
 a:["i = m·z / P_h, gdzie z to krotność, P_h skok",
    "i = P_h / (m·z), jako odwrotność wysokości",
    "i = m / (z·P_h), niezależnie od krotności",
    "i = P_h·z / m, proporcjonalnie do skoku"],c:0,
 e:"Liczba czynnych zwojów i = m·z/P_h (m – wysokość nakrętki, z – krotność, P_h – skok gwintu)."},
{t:"gwint",q:"Dla normalnych łączników gwintowych w połączeniach spoczynkowych przyjmuje się:",
 a:["m = 0,3d, gdyż wystarczają trzy zwoje gwintu",
    "m = 0,8d, zwykle bez obliczeń sprawdzających",
    "m = 1,5d, ze względu na wysokie naciski zwojów",
    "m = 2,5d, aby maksymalnie odciążyć pierwszy zwój"],c:1,
 e:"Dla normalnych łączników spoczynkowych przyjmuje się m = 0,8d bez dodatkowych obliczeń."},
{t:"gwint",q:"Najwyższe wartości nacisków dopuszczalnych p_dop (k_d) mają połączenia:",
 a:["ruchowe, pracujące stale w przekładniach śrubowych",
    "spoczynkowe, łączone na stałe elementami złącznymi",
    "półruchowe, poruszane jedynie sporadycznie w pracy",
    "napędowe, obciążane jednocześnie udarowo i cieplnie"],c:1,
 e:"Połączenia spoczynkowe dopuszczają najwyższe naciski; ruchowe (przekładnie) — najniższe."},
{t:"gwint",q:"Które zestawienie poprawnie wymienia cztery przypadki obciążenia śruby?",
 a:["osiowa; osiowa z gnącym; poprzeczna; cieplna zmienna",
    "rozciągająca; ścinająca; gnąca; wyłącznie cieplna",
    "osiowa; osiowa ze skręcającym; napięta wstępnie z osiową; poprzeczna",
    "statyczna; dynamiczna; udarowa; zmęczeniowa cykliczna o stałej amplitudzie"],c:2,
 e:"Wyróżnia się: obciążenie siłą osiową; siłą osiową i momentem skręcającym; napięcie wstępne + siła osiowa; siła poprzeczna."},
{t:"gwint",q:"Hak dźwigowy z gwintem jest typowym przykładem śruby obciążonej:",
 a:["wyłącznie siłą osiową rozciągającą rdzeń",
    "siłą osiową oraz momentem skręcającym razem",
    "głównie momentem gnącym od mimośrodu siły",
    "siłą poprzeczną ścinającą przekrój rdzenia"],c:0,
 e:"Hak dźwigowy przenosi tylko siłę osiową (rozciąganie) — bez momentu skręcającego."},
{t:"gwint",q:"Średnicę rdzenia śruby obciążonej osiowo z warunku rozciągania wyznacza wzór:",
 a:["d_r = 1,13·√(Q/k_r), z warunku na rozciąganie",
    "d_r = 0,25·√(Q·k_r), z warunku na ścinanie",
    "d_r = 1,13·√(k_r/Q), odwrotnie do obciążenia",
    "d_r = 0,8·√(Q·E), zależnie od modułu Younga"],c:0,
 e:"Z warunku σ_r = Q/(πd_r²/4) ≤ k_r wynika d_r = 1,13·√(Q/k_r)."},
{t:"gwint",q:"Śruba podnośnikowa (napędowa) podlega złożonemu stanowi naprężeń, którego warunek to:",
 a:["σ_z = σ_r + τ ≤ k_r, jako prosta suma naprężeń",
    "σ_z = √(σ_r² + (k_{r,c}/k_s·τ)²) ≤ k_{r,c}",
    "σ_z = σ_r − τ ≤ k_r, jako różnica naprężeń",
    "σ_z = √(σ_r·τ) ≤ k_r, jako średnia geometryczna"],c:1,
 e:"Rdzeń jest jednocześnie rozciągany (σ_r) i skręcany (τ); warunek to naprężenie zastępcze σ_z = √(σ_r² + (k_{r,c}/k_s·τ)²) ≤ k_{r,c}."},
{t:"gwint",q:"Naprężenie dopuszczalne na rozciąganie przy obciążeniu statycznym przyjmuje postać:",
 a:["k_r = R_e · x_e, jako iloczyn z zapasem",
    "k_r = R_e / x_e, gdzie x_e = 1,3 ÷ 2,5",
    "k_r = R_m / x_e, odniesione do wytrzymałości",
    "k_r = Z_rc / x_z, właściwe dla obciążeń zmiennych"],c:1,
 e:"Dla obciążeń statycznych k_r = R_e/x_e przy x_e = 1,3 ÷ 2,5 (dla zmiennych: k_{rj} = Z_rc/x_z)."},
{t:"gwint",q:"Długie śruby ściskane sprawdza się dodatkowo na wyboczenie z warunku stateczności:",
 a:["σ_c ≤ σ_kr / x_w, gdzie x_w = 6 ÷ 8",
    "σ_c ≤ σ_kr · x_w, jako iloczyn z zapasem",
    "σ_c ≥ σ_kr / x_w, dla zachowania nośności",
    "σ_c ≤ R_e / x_e, niezależnie od smukłości"],c:0,
 e:"Warunek stateczności: σ_c ≤ σ_kr/x_w, gdzie współczynnik bezpieczeństwa x_w = 6 ÷ 8."},
{t:"gwint",q:"Wzór Eulera (σ_kr = π²E/λ²) obowiązuje w zakresie wyboczenia:",
 a:["sprężysto-plastycznego, gdy smukłość λ < λ_gr",
    "sprężystego, gdy smukłość λ ≥ λ_gr",
    "statycznego, niezależnie od smukłości pręta",
    "zmęczeniowego, przy obciążeniach zmiennych"],c:1,
 e:"Wzór Eulera obowiązuje w zakresie sprężystym, czyli dla smukłości λ ≥ λ_gr."},
{t:"gwint",q:"Wzór Tetmajera (σ_kr = σ_o − bλ) stosuje się przy wyboczeniu:",
 a:["sprężystym, gdy smukłość λ przekracza λ_gr",
    "sprężysto-plastycznym, gdy smukłość λ < λ_gr",
    "wyłącznie statycznym przy stałym obciążeniu",
    "zmęczeniowym przy obciążeniach cyklicznych"],c:1,
 e:"Wzór Tetmajera obowiązuje w zakresie sprężysto-plastycznym, dla λ < λ_gr (σ_o = R_e)."},
{t:"gwint",q:"Smukłość śruby λ oraz minimalny promień bezwładności i_min wyrażają się jako:",
 a:["λ = μ_w·l / i_min, przy czym i_min = 0,25·d_r",
    "λ = i_min / (μ_w·l), przy czym i_min = 0,5·d_r",
    "λ = l / (μ_w·i_min), przy czym i_min = d_r",
    "λ = μ_w·i_min / l, przy czym i_min = 0,1·d_r"],c:0,
 e:"Smukłość λ = μ_w·l/i_min, a dla przekroju kołowego i_min = 0,25·d_r."},
{t:"gwint",q:"Współczynnik swobodnej długości μ_w dla śruby utwierdzonej obustronnie (oba końce) wynosi:",
 a:["μ_w = 2,0, jak dla wspornika swobodnego",
    "μ_w = 1,0, jak dla pręta przegubowo-przegubowego",
    "μ_w = 0,7, dla utwierdzenia i przegubu",
    "μ_w = 0,5, dla obustronnego utwierdzenia"],c:3,
 e:"Dla obustronnego utwierdzenia μ_w = 0,5; dla wspornika μ_w = 2, przegub-przegub μ_w = 1."},
{t:"gwint",q:"Naprężenia gnące w śrubie od nieprostopadłości oporowej opisuje uproszczony wzór:",
 a:["σ_g = (1/2)·(d_r/l)·E·δ, gdzie δ to kąt ugięcia",
    "σ_g = (1/2)·(l/d_r)·E·δ, odwrotnie do średnicy",
    "σ_g = 2·(d_r/l)·E·δ, ze stałą równą dwa",
    "σ_g = (1/2)·(d_r/l)·δ, bez modułu sprężystości"],c:0,
 e:"Z linii ugięcia: σ_g = ½·(d_r/l)·E·δ — rośnie z modułem E i kątem ugięcia δ, maleje ze smukłością."},
{t:"gwint",q:"Jaki kąt ugięcia śruby δ uznaje się za bezpieczny, a jaki za bardzo groźny?",
 a:["bezpieczny do 0,5°; bardzo groźny powyżej 3°",
    "bezpieczny do 5°; bardzo groźny powyżej 10°",
    "bezpieczny do 0,1°; bardzo groźny powyżej 1°",
    "bezpieczny do 2°; bardzo groźny powyżej 20°"],c:0,
 e:"Kąt do 0,5° jest bezpieczny, 1–2° niebezpieczny zmęczeniowo, a powyżej 3° daje wysokie ryzyko uszkodzenia."},
{t:"gwint",q:"Aby zmniejszyć naprężenia gnące, śruba powinna mieć budowę:",
 a:["krótką i sztywną, o jak najmniejszej smukłości",
    "smukłą i podatną, o dużym stosunku l/d_r",
    "z żeliwa szarego zamiast ze stali stopowej",
    "o znacznie powiększonej średnicy rdzenia d_r"],c:1,
 e:"Im większy stosunek l/d_r (śruba smuklejsza, sprężystsza), tym mniejsze naprężenia gnące."},
{t:"gwint",q:"Całkowita siła w śrubie napiętej wstępnie w stanie roboczym wynosi:",
 a:["Q = Q_w + χ·Q_p, gdzie χ to współczynnik obciążenia",
    "Q = Q_w − χ·Q_p, jako różnica sił montażowych",
    "Q = χ·(Q_w + Q_p), proporcjonalnie do sumy",
    "Q = Q_w · Q_p, jako iloczyn obu składowych"],c:0,
 e:"W stanie roboczym Q = Q_w + χ·Q_p, gdzie χ to współczynnik obciążenia złącza śrubowego."},
{t:"gwint",q:"Zacisk resztkowy kołnierzy Q_z w połączeniu napiętym wstępnie dobiera się, aby:",
 a:["zminimalizować masę zastosowanej śruby",
    "zapewnić szczelność wykonanego połączenia",
    "zwiększyć skok gwintu współpracującej nakrętki",
    "całkowicie usunąć tarcie między zwojami gwintu"],c:1,
 e:"Q_z musi pozostać dodatni, by kołnierze były wciąż dociśnięte — to warunek szczelności złącza."},
{t:"gwint",q:"Sztywność śruby o stałym przekroju wyraża zależność:",
 a:["C_s = F_s·E_s / l_s, rosnąca z przekrojem rdzenia",
    "C_s = l_s / (F_s·E_s), malejąca z przekrojem",
    "C_s = E_s / (F_s·l_s), niezależna od długości",
    "C_s = F_s·l_s / E_s, rosnąca z długością śruby"],c:0,
 e:"Sztywność śruby o stałym przekroju C_s = F_s·E_s/l_s (rośnie z polem przekroju, maleje z długością)."},

/* ===================== POŁĄCZENIA SPAWANE ===================== */
{t:"spaw",q:"Zasadniczym, nośnym elementem złącza spawanego jest spoina powstała z:",
 a:["nitów osadzonych w otworach łączonych blach",
    "kleju konstrukcyjnego naniesionego między elementy",
    "stopiwa oraz nadtopionych materiałów rodzimych",
    "sprasowanych na zimno powierzchni elementów"],c:2,
 e:"Spoina powstaje przez stopienie i krzepnięcie stopiwa (materiału dodatkowego) oraz materiałów rodzimych."},
{t:"spaw",q:"Który zestaw poprawnie wymienia podstawowe rodzaje spoin?",
 a:["czołowe, pachwinowe oraz otworowe",
    "wzdłużne, poprzeczne oraz skośne",
    "jednostronne, dwustronne oraz pierścieniowe",
    "twarde, miękkie oraz ulepszane cieplnie"],c:0,
 e:"Podstawowe rodzaje spoin to: czołowe, pachwinowe i otworowe."},
{t:"spaw",q:"Kształt rowka spoiny czołowej wykazuje podobieństwo do wielkich liter:",
 a:["A, B, C oraz D",
    "L, M, N oraz T",
    "O, P, Q oraz R",
    "I, V, Y, X, U, J, K"],c:3,
 e:"Zarys rowka spoiny czołowej przypomina litery I, V, Y, X, U, J, K (zależnie od grubości i ukosowania)."},
{t:"spaw",q:"Naprężenie dopuszczalne w spoinie wg starszych norm opisuje wzór:",
 a:["k' = z_o·z·k_r, jako iloczyn trzech czynników",
    "k' = z_o + z + k_r, jako suma składowych",
    "k' = z_o·z / k_r, jako iloraz przez k_r",
    "k' = k_r / (z_o·z), odwrotnie do współczynników"],c:0,
 e:"k' = z_o·z·k_r — gdzie z_o to wsp. wytrzymałości statycznej, z jakości spoiny, k_r naprężenie dopuszczalne materiału."},
{t:"spaw",q:"Współczynnik wytrzymałości statycznej z_o przyjmuje wartości m.in.:",
 a:["0,75 dla rozciągania oraz 0,65 dla ścinania",
    "1,00 dla rozciągania oraz 0,90 dla ścinania",
    "0,50 dla rozciągania oraz 0,30 dla ścinania",
    "0,20 dla rozciągania oraz 0,10 dla ścinania"],c:0,
 e:"z_o wynosi: 0,75 (rozciąganie), 0,8 (ściskanie i zginanie), 0,65 (ścinanie)."},
{t:"spaw",q:"Wartość współczynnika jakości spoiny z (0,5 ÷ 1,0) zależy od:",
 a:["temperatury panującej w otoczeniu złącza",
    "barwy powłoki ochronnej naniesionej na spoinę",
    "konstrukcji złącza i staranności wykonania spoiny",
    "wyłącznie od prędkości prowadzenia łuku spawalniczego"],c:2,
 e:"z zależy od konstrukcji i staranności wykonania spoiny (np. kontroli i defektoskopii)."},
{t:"spaw",q:"Wg normy PN-90/B-03200 naprężenie dopuszczalne w spoinie wyraża się jako:",
 a:["k' = α·k = α·R_e/x_e, wg metody stanów granicznych",
    "k' = z_o·z·k_r, wg metody naprężeń dopuszczalnych",
    "k' = α + k, jako suma składowych granicznych",
    "k' = R_e·x_e, jako iloczyn z zapasem bezpieczeństwa"],c:0,
 e:"Wg PN-90/B-03200 (metoda stanów granicznych) k' = α·k = α·R_e/x_e, gdzie α to wsp. wytrzymałości statycznej spoiny."},
{t:"spaw",q:"Wg PN-90/B-03200 dla obciążeń zmiennych współczynnik bezpieczeństwa x_e przyjmuje wartość:",
 a:["x_e = 1,0, identyczną jak dla obciążeń stałych",
    "x_e = 1,6, podwyższoną względem obciążeń stałych",
    "x_e = 0,5, obniżoną dla spoin pachwinowych",
    "x_e = 4,0, jak dla obciążeń udarowych"],c:1,
 e:"Dla obciążeń zmiennych wg PN-90/B-03200 przyjmuje się x_e = 1,6."},
{t:"spaw",q:"O ile obniża się współczynnik α dla spoin wykonywanych w pozycji pułapowej?",
 a:["o 10%, dokładnie tak samo jak dla spoin montażowych wykonywanych ręcznie",
    "o 20%, ze względu na trudniejsze warunki wykonania",
    "o 30%, czyli sumarycznie z montażowymi",
    "wcale, gdyż pozycja nie ma znaczenia"],c:1,
 e:"Współczynnik α obniża się: o 10% dla spoin montażowych, o 20% dla pułapowych, o 30% dla obu przypadków łącznie."},
{t:"spaw",q:"Spoinę czołową obciążoną momentem gnącym i siłą ścinającą sprawdza się warunkiem:",
 a:["σ_z = σ_g + τ ≤ k'_g, jako prosta suma",
    "σ_z = √(σ_g² + 3τ²) ≤ k'_g, jako naprężenie zastępcze",
    "σ_z = σ_g − τ ≤ k'_g, jako różnica naprężeń",
    "σ_z = √(σ_g·τ) ≤ k'_g, jako średnia geometryczna"],c:1,
 e:"Dla spoiny czołowej z gnącym i ścinającym warunek bezpieczeństwa to σ_z = √(σ_g² + 3τ²) ≤ k'_g."},
{t:"spaw",q:"Spoinę pachwinową obciążoną momentem gnącym i siłą poprzeczną sprawdza się warunkiem:",
 a:["τ_z = √(τ_M² + τ_Q²) ≤ k'_t, jako wypadkowa naprężeń",
    "τ_z = τ_M + τ_Q ≤ k'_t, jako prosta suma składowych",
    "τ_z = √(τ_M² − τ_Q²) ≤ k'_t, jako różnica pod pierwiastkiem",
    "τ_z = τ_M·τ_Q ≤ k'_t, jako iloczyn naprężeń"],c:0,
 e:"Dla spoiny pachwinowej warunek to τ_z = √(τ_M² + τ_Q²) ≤ k'_t (wypadkowa naprężeń stycznych)."},
{t:"spaw",q:"Skrót SWC w połączeniu spawanym oznacza:",
 a:["strefę wpływu ciepła wokół spoiny",
    "standardowy współczynnik ciągliwości stali",
    "stan wytrzymałości chwilowej złącza",
    "spoinę współczynnikową typu czołowego"],c:0,
 e:"SWC to strefa wpływu ciepła — obszar materiału rodzimego o zmienionej strukturze obok spoiny."},
{t:"spaw",q:"Wg Eurokodu 3 efektywną grubość spoiny pachwinowej a definiuje się jako:",
 a:["pełną szerokość cieńszego łączonego elementu",
    "wysokość największego trójkąta wpisanego w przekrój",
    "całkowitą długość lica spoiny wzdłuż złącza",
    "sumę grubości obu łączonych ze sobą elementów"],c:1,
 e:"Grubość obliczeniowa a to wysokość największego trójkąta wpisanego w przekrój poprzeczny spoiny."},
{t:"spaw",q:"Wg Eurokodu 3 obliczeniowe pole przekroju spoiny pachwinowej przyjmuje się jako:",
 a:["A = Σ a·l_eff, gdzie l_eff to długość efektywna",
    "A = Σ a + l_eff, jako sumę grubości i długości",
    "A = a / l_eff, jako iloraz grubości przez długość",
    "A = π·a·l_eff, jak dla przekroju pierścieniowego"],c:0,
 e:"Pole obliczeniowe A = Σ a·l_eff (grubość efektywna razy długość efektywna spoiny)."},
{t:"spaw",q:"Które wymaganie geometryczne dla spoiny pachwinowej wg Eurokodu 3 jest poprawne?",
 a:["a ≥ 3 mm oraz a ≤ 0,7·t_min (minimum i maksimum)",
    "a ≥ 10 mm oraz a ≥ t_max (zawsze grubsza)",
    "a ≤ 1 mm oraz a ≥ 0,9·t_max (cienkie blachy)",
    "a = t_min dokładnie, bez żadnej tolerancji"],c:0,
 e:"Minimum technologiczne a ≥ 3 mm (stabilność łuku), a maksimum skurczowe a ≤ 0,7·t_min (ochrona przed skurczem)."},
{t:"spaw",q:"Do obliczeń wg Eurokodu 3 uwzględnia się tylko spoiny pachwinowe o długości:",
 a:["l_eff ≥ 30 mm oraz l_eff ≥ 6a jednocześnie",
    "l_eff ≥ 5 mm oraz l_eff ≥ 2a jednocześnie",
    "l_eff ≥ 100 mm oraz l_eff ≥ 20a jednocześnie",
    "dowolnej, gdyż długość nie ma znaczenia"],c:0,
 e:"Uwzględnia się spoiny o l_eff ≥ 30 mm oraz l_eff ≥ 6a — krótsze pomija się jako niemiarodajne."},
{t:"spaw",q:"Czym różni się podejście Eurokodu 3 od normy PN-90/B-03200 w projektowaniu spoin?",
 a:["Eurokod 3 stosuje metodę stanów granicznych, PN — naprężeń dopuszczalnych",
    "Eurokod 3 stosuje metodę naprężeń dopuszczalnych, PN — stanów granicznych",
    "obie normy stosują wyłącznie metodę naprężeń dopuszczalnych",
    "obie normy stosują wyłącznie metodę stanów granicznych"],c:0,
 e:"Eurokod 3 opiera się na metodzie stanów granicznych, natomiast starsze ujęcie PN — na metodzie naprężeń dopuszczalnych."},
{t:"spaw",q:"Sprężysto-plastyczny stan odkształceń w spoinie jest:",
 a:["dopuszczalny przy obciążeniach statycznych, niepożądany przy zmęczeniowych",
    "zawsze całkowicie niedopuszczalny, niezależnie od rodzaju przyłożonego obciążenia",
    "występujący wyłącznie w spoinach typu otworowego",
    "zawsze korzystny, bo zwiększa trwałość zmęczeniową"],c:0,
 e:"Przy obciążeniach statycznych jest akceptowalny (mała deformacja), ale przy zmiennych obniża trwałość."},

/* ===================== SPRZĘGŁA ===================== */
{t:"sprz",q:"Sprzęgło to zespół służący do łączenia wałów i przenoszenia momentu obrotowego:",
 a:["z trwałą zmianą jego wartości oraz kierunku",
    "bez trwałej zmiany jego wartości ani kierunku",
    "wyłącznie przy hamowaniu członu ruchomego",
    "ze zmianą prędkości kątowej i wartości momentu"],c:1,
 e:"Sprzęgło przenosi moment obrotowy bez trwałej zmiany jego wartości i kierunku (inaczej niż przekładnia)."},
{t:"sprz",q:"Nominalny moment obrotowy sprzęgła wyznacza się z mocy i prędkości wzorem:",
 a:["M = N/ω = 9550·N/n, gdzie N to moc, n obroty",
    "M = ω/N = N·n/9550, odwrotnie do mocy",
    "M = N·ω = N·n·9550, jako iloczyn wielkości",
    "M = z·m, niezależnie od mocy i prędkości"],c:0,
 e:"Moment M = N/ω; w jednostkach praktycznych M = 9550·N/n (N w kW, n w obr/min)."},
{t:"sprz",q:"Maksymalny moment przenoszony przez sprzęgło uwzględnia nadwyżkę dynamiczną wzorem:",
 a:["M_max = K + M, jako suma momentu i współczynnika",
    "M_max = K · M, gdzie K to współczynnik przeciążenia",
    "M_max = M / K, jako iloraz przez współczynnik",
    "M_max = K² · M, z kwadratem współczynnika"],c:1,
 e:"M_max = K·M, gdzie K to współczynnik przeciążenia zależny od charakteru pracy maszyny."},
{t:"sprz",q:"W sprzęgłach, w których moment przenoszony jest przez tarcie, musi być spełniony warunek:",
 a:["M_T ≥ K · M (moment tarcia większy od maksymalnego)",
    "M_T ≤ K · M (moment tarcia mniejszy od maksymalnego)",
    "M_T = 0 (brak udziału tarcia w przenoszeniu)",
    "M_T = R_e / x_e (zależnie od wytrzymałości)"],c:0,
 e:"W sprzęgłach ciernych moment tarcia musi spełniać M_T ≥ K·M, by nie wystąpił poślizg."},
{t:"sprz",q:"Współczynnik przeciążenia dla sprzęgieł sztywnych i samonastawnych przyjmuje postać:",
 a:["K = K₁ + K₂ (suma składowych napędu i maszyny)",
    "K = K₁ · K₂ · K₃ (iloczyn trzech składowych)",
    "K = K₁ / (K₂·K₃) (iloraz składowych)",
    "K = 1,33·K₁·K₂·K₃ (ze stałym mnożnikiem)"],c:0,
 e:"Dla sprzęgieł sztywnych i samonastawnych K = K₁ + K₂ (K₁ od silnika, K₂ od maszyny napędzanej)."},
{t:"sprz",q:"Współczynnik przeciążenia dla sprzęgieł przegubowych (Cardana) ma postać:",
 a:["K = K₁ + K₂ (jak dla sztywnych)",
    "K = 1,33·K₁·K₂·K₃ (ze współczynnikiem 1,33)",
    "K = K₁ / (K₂·K₃) (jak dla ciernych)",
    "K = (K₁ + K₂)·K₃ (jak dla jednokierunkowych)"],c:1,
 e:"Dla sprzęgieł Cardana K = 1,33·K₁·K₂·K₃, gdzie K₃ zależy od kąta przekoszenia wałów."},
{t:"sprz",q:"Współczynnik przeciążenia dla sprzęgieł ciernych przyjmuje postać:",
 a:["K = K₁ + K₂, jako prosta suma składowych",
    "K = K₁ / (K₂·K₃), gdzie K₃ zależy od poślizgu",
    "K = K₁·K₂·K₃, jako iloczyn trzech składowych",
    "K = 1,33·K₁·K₂, ze stałym mnożnikiem"],c:1,
 e:"Dla sprzęgieł ciernych K = K₁/(K₂·K₃), gdzie K₂ zależy od prędkości poślizgu, K₃ od liczby włączeń."},
{t:"sprz",q:"Norma DIN 740-2 ujmuje współczynnik pracy (przeciążenia) jako:",
 a:["K = S_A·S_Z·S_t, przy warunku M_znam ≥ M_max",
    "K = S_A + S_Z + S_t, jako sumę współczynników",
    "K = S_A / (S_Z·S_t), jako iloraz składowych",
    "K = R_e/x_e, jak dla naprężeń dopuszczalnych"],c:0,
 e:"Wg DIN 740-2 K = S_A·S_Z·S_t (uderzeń, częstości rozruchów, temperatury), a dobór sprawdza M_znam ≥ M_max."},
{t:"sprz",q:"Współczynnik S_t w doborze sprzęgieł podatnych wg DIN 740-2 uwzględnia:",
 a:["liczbę uderzeń przenoszonych od strony napędu oraz maszyny roboczej",
    "częstotliwość rozruchów i zatrzymań maszyny",
    "spadek wytrzymałości wkładki przy wyższej temperaturze",
    "barwę i materiał obudowy zastosowanego sprzęgła"],c:2,
 e:"S_t (temperatury pracy) uwzględnia spadek wytrzymałości elastycznej wkładki w podwyższonej temperaturze."},
{t:"sprz",q:"Które sprzęgła zaliczamy do nierozłącznych samonastawnych?",
 a:["kłowe, krzyżakowe, zębate oraz łańcuchowe",
    "tarczowe cierne, wielopłytkowe oraz stożkowe",
    "bezpieczeństwa, odśrodkowe oraz jednokierunkowe",
    "kołnierzowe sztywne oraz tulejowe kołkowe"],c:0,
 e:"Sprzęgła samonastawne to m.in. kłowe, krzyżakowe (Oldhama), zębate i łańcuchowe — kompensują niewspółosiowość."},
{t:"sprz",q:"Sprzęgła podatne stosuje się przede wszystkim, gdy w układzie:",
 a:["wymagana jest pełna sztywność i współosiowość",
    "występują duże drgania skrętne wymagające tłumienia",
    "panują wyłącznie obciążenia czysto statyczne",
    "w ogóle nie jest przenoszony moment obrotowy"],c:1,
 e:"Sprzęgła podatne (z wkładką metalową lub gumową) tłumią drgania skrętne i łagodzą udary."},
{t:"sprz",q:"Sprzęgło podatne powinno być tak dobrane, aby liczba n = T/τ spełniała:",
 a:["n = n_gr ≈ 1, czyli praca w rezonansie",
    "n ≥ n_gr ≈ 12 ÷ 20, czyli poza strefą rezonansu",
    "n ≤ 1, czyli poniżej częstości wymuszenia",
    "n ≈ 100, niezależnie od bezwładności mas"],c:1,
 e:"Sprzęgło podatne dobiera się tak, by n = T/τ ≥ n_gr ≈ 12 ÷ 20 — z dala od rezonansu drgań skrętnych."},
{t:"sprz",q:"Pojedyncze sprzęgło przegubowe Cardana przenosi ruch:",
 a:["zawsze idealnie jednostajnie, bez wahań prędkości",
    "niejednostajnie — ze zmienną prędkością wału biernego",
    "bez przenoszenia jakiegokolwiek momentu obrotowego",
    "wyłącznie przy pełnej współosiowości obu wałów"],c:1,
 e:"Pojedynczy przegub Cardana daje niejednostajny bieg wału biernego (zmienna ω₂ przy stałej ω₁)."},
{t:"sprz",q:"Niejednostajność biegu usuwa się stosując podwójne sprzęgło Cardana z wałkiem pośrednim, gdy:",
 a:["kąty załamania na obu przegubach są jednakowe",
    "kąty załamania na obu przegubach są różne",
    "wałek pośredni jest możliwie najdłuższy",
    "widełki obu przegubów są wzajemnie prostopadłe"],c:0,
 e:"Synchronizacja (jednostajny bieg) wymaga równych kątów na obu przegubach i właściwego ustawienia widełek."},
{t:"sprz",q:"Sprzęgła rozłączne sterowane, włączane synchronicznie, to sprzęgła:",
 a:["kłowe oraz zębate (kształtowe)",
    "tarczowe cierne oraz wielopłytkowe",
    "stożkowe cierne oraz bezpieczeństwa",
    "odśrodkowe oraz jednokierunkowe"],c:0,
 e:"Włączane synchronicznie są sprzęgła kształtowe (kłowe, zębate); cierne (tarczowe, wielopłytkowe, stożkowe) — asynchronicznie."},
{t:"sprz",q:"W sprzęgle ciernym włączalnym znak +/− we wzorze na siłę P_w odpowiada:",
 a:["znakowi plus przy włączaniu, minus przy rozłączaniu sprzęgła",
    "znakowi plus przy rozłączaniu, minus przy włączaniu sprzęgła",
    "znakowi plus przy pracy ustalonej, minus przy rozruchu",
    "znakom momentu obrotowego, bez związku z włączaniem"],c:0,
 e:"We wzorze P_w = 2M[tg(α±ρ)/D_śr ± μ/d] znak plus dotyczy włączania, a minus rozłączania sprzęgła."},
{t:"sprz",q:"Sprzęgło bezpieczeństwa (kulkowe, wielopłytkowe) po przeciążeniu:",
 a:["trwale i nieodwracalnie blokuje oba wały",
    "ślizga się, ograniczając przenoszony moment",
    "samoczynnie zwiększa przenoszony moment",
    "zmienia kierunek obrotów wału biernego"],c:1,
 e:"Po przekroczeniu momentu granicznego następuje poślizg i spadek momentu — chroni to układ przed przeciążeniem."},
{t:"sprz",q:"Do sprzęgieł samoczynnych zaliczamy sprzęgła:",
 a:["sztywne, podatne oraz samonastawne",
    "synchroniczne oraz kształtowe zębate",
    "bezpieczeństwa, odśrodkowe oraz jednokierunkowe",
    "tulejowe kołkowe oraz tarczowe kołnierzowe"],c:2,
 e:"Sprzęgła samoczynne to: bezpieczeństwa (przeciążeniowe), odśrodkowe i jednokierunkowe."},
{t:"sprz",q:"Sprzęgło odśrodkowe załącza się samoczynnie pod wpływem:",
 a:["wzrostu prędkości obrotowej (sił odśrodkowych)",
    "przekroczenia granicznego momentu obrotowego",
    "zmiany kierunku obrotów wału czynnego",
    "spadku temperatury wkładki elastycznej"],c:0,
 e:"Sprzęgło odśrodkowe załącza się przy odpowiednio wysokich obrotach — dzięki siłom odśrodkowym dociskającym elementy."},
{t:"sprz",q:"W sprzęgle nasadzanym ze śrubami pasowanymi ciasno moment jest przenoszony przez:",
 a:["siły tarcia między tarczami kołnierzy",
    "siły ścinające działające na każdą ze śrub",
    "pole elektromagnetyczne wytworzone w cewce",
    "krążący strumień cieczy roboczej"],c:1,
 e:"Przy śrubach pasowanych ciasno moment przenosi siła ścinająca śruby (M_SP = z·P_śruby·D₀/2)."},

/* ===================== HAMULCE ===================== */
{t:"ham",q:"Hamulce są elementami układu napędowego realizującymi zadanie poprzez:",
 a:[    "zazębienie wielu współpracujących walcowych kół zębatych przekładni",
    "sprzężenie cierne członu ruchomego z nieruchomym",
    "pole magnetyczne wytwarzane wokół wału",
    "krążący strumień cieczy chłodzącej układ"],c:1,
 e:"Hamowanie (zatrzymanie, regulacja, utrzymanie położenia) realizuje sprzężenie cierne członu ruchomego z nieruchomym."},
{t:"ham",q:"Podstawowa różnica między hamulcem a sprzęgłem polega na tym, że w hamulcu:",
 a:["oba człony swobodnie obracają się względem siebie",
    "jeden z członów połączony jest z elementem nieruchomym",
    "nie występuje w ogóle zjawisko tarcia okładzin",
    "przenoszony moment jest zawsze znacznie większy"],c:1,
 e:"W hamulcu jeden człon jest nieruchomy; w sprzęgle oba człony mogą się obracać."},
{t:"ham",q:"Przy projektowaniu hamulca zakłada się, że moment tarcia M_T względem momentu M_o wynosi:",
 a:["M_T = (1,75 ÷ 2,5)·M_o, z zapasem na pewność hamowania",
    "M_T = (0,3 ÷ 0,5)·M_o, jako ułamek momentu",
    "M_T = M_o dokładnie, bez żadnego zapasu",
    "M_T = (5 ÷ 8)·M_o, z bardzo dużym, nieuzasadnionym zapasem bezpieczeństwa"],c:0,
 e:"Przyjmuje się M_T = (1,75 ÷ 2,5)·M_o — zapas zapewnia pewne zahamowanie bębna."},
{t:"ham",q:"Który podział hamulców stosowanych w układach napędowych jest poprawny?",
 a:["sztywne, podatne oraz cierne samonastawne",
    "czołowe, śrubowe oraz ślimakowe walcowe",
    "klockowe, szczękowe, tarczowe oraz taśmowe",
    "osiowe, promieniowe oraz kątowe przegubowe"],c:2,
 e:"Hamulce dzielą się na: klockowe, szczękowe (bębnowe), tarczowe/stożkowe oraz taśmowe."},
{t:"ham",q:"W pojedynczym hamulcu klockowym siła N normalna do bębna wynika z zależności:",
 a:["N = M_T/(μR), gdzie μ to współczynnik tarcia",
    "N = M_T·μR, jako iloczyn momentu i tarcia",
    "N = μR/M_T, odwrotnie do momentu tarcia",
    "N = M_T/R + μ, jako suma składników"],c:0,
 e:"Z M_T = T·R = μN·R wynika N = M_T/(μR)."},
{t:"ham",q:"W hamulcu klockowym z dźwignią podpartą w punkcie A₁ siła P jest niezależna od kierunku obrotów, gdy:",
 a:["punkt podparcia przeniesiono do punktu A₂ (na osi siły N)",
    "ramię c jest znacznie większe od ramienia b",
    "współczynnik tarcia μ jest bliski zeru",
    "klocek dociskany jest jednocześnie dwiema niezależnymi dźwigniami"],c:0,
 e:"Przeniesienie podparcia do A₂ (na linię działania N) daje P = M_T/(μR)·(b/a), niezależne od kierunku obrotów."},
{t:"ham",q:"Hamulec klockowy zaczyna działać jak zapadka (samohamowność), gdy:",
 a:["b > μc, czyli ramię b przewyższa iloczyn μc",
    "b < μc, czyli ramię b jest mniejsze od μc",
    "b = a, czyli ramiona dźwigni są równe",
    "μ = 0, czyli tarcie całkowicie zanika"],c:1,
 e:"Gdy b < μc, siła P_A1 staje się ujemna — hamulec samoczynnie się zaciska i działa jak zapadka."},
{t:"ham",q:"W szczękowym hamulcu bębnowym w układzie symetrycznym siły normalne N₁ i N₂ szczęk są:",
 a:["jednakowe, ponieważ obie szczęki mają identyczną konstrukcję",
    "nierówne, w stosunku N₁/N₂ = (e₂−μe₃)/(e₂+μe₃)",
    "zawsze równe zeru przy hamowaniu",
    "niezależne od kierunku obrotów bębna"],c:1,
 e:"W układzie symetrycznym N₁ ≠ N₂; ze sumy momentów N₁/N₂ = (e₂−μe₃)/(e₂+μe₃) — jedna szczęka jest nabiegająca."},
{t:"ham",q:"W hamulcu taśmowym wartość siły naciągu taśmy opisuje wzór:",
 a:["S₁ = S₂ + μα, jako suma składowych naciągu",
    "S₁ = S₂·e^(μα), zgodnie ze wzorem Eulera",
    "S₁ = S₂/μ, jako iloraz przez współczynnik tarcia",
    "S₁ = μ·N·R, jako iloczyn siły i promienia"],c:1,
 e:"Naciąg taśmy zmienia się wykładniczo wg Eulera: S₁ = S₂·e^(μα)."},
{t:"ham",q:"Moment hamujący hamulca taśmowego można zapisać jako:",
 a:["M_H = (S₁ − S₂)·D_H/2 = (e^μα − 1)·S₂·D_H/2",
    "M_H = (S₁ + S₂)·D_H, jako suma naciągów",
    "M_H = S₁·S₂·D_H/2, jako iloczyn naciągów",
    "M_H = (S₁ − S₂)/D_H, odwrotnie do średnicy"],c:0,
 e:"M_H = (S₁ − S₂)·D_H/2 = (e^μα − 1)·S₂·D_H/2 (D_H — średnica bębna)."},
{t:"ham",q:"W hamulcu taśmowym zwykłym praktyczne przełożenie dźwigni l/a przyjmuje się w zakresie:",
 a:["l/a = 3 ÷ 6, jako kompromis siły i gabarytu",
    "l/a = 0,1 ÷ 0,3, dla małych sił obsługi",
    "l/a = 20 ÷ 50, dla bardzo dużych bębnów",
    "l/a = 1 dokładnie, bez żadnego przełożenia"],c:0,
 e:"W hamulcu taśmowym zwykłym (G = S₂·a/l) stosuje się przełożenie dźwigni l/a = 3 ÷ 6."},
{t:"ham",q:"Hamulec taśmowy różnicowy może działać jak zapadka (samohamowny), gdy spełniony jest warunek:",
 a:["a₂ ≤ a₁·e^(μα), czyli ramię a₂ jest dostatecznie małe",
    "a₂ ≥ a₁·e^(μα), czyli ramię a₂ jest dostatecznie duże",
    "a₁ = a₂, czyli oba ramiona są jednakowe",
    "μ = 0, czyli tarcie całkowicie zanika"],c:0,
 e:"Dla hamulca różnicowego, gdy a₂ ≤ a₁·e^(μα), siła G staje się niedodatnia — hamulec działa jak zapadka."},
{t:"ham",q:"Hamulce taśmowe stosuje się w praktyce przede wszystkim jako:",
 a:["hamulce pomocnicze oraz postojowe",
    "główne hamulce robocze precyzyjnych obrabiarek",
    "sprzęgła rozruchowe dużych silników spalinowych",
    "elementy uszczelniające szybkoobrotowe wały"],c:0,
 e:"Hamulce taśmowe wykorzystuje się głównie jako pomocnicze i postojowe (np. kolejki górskie)."},
{t:"ham",q:"Rolę hamulca może spełniać większość sprzęgieł:",
 a:["nierozłącznych, połączonych ze sobą trwale",
    "rozłącznych, dających się rozłączyć w pracy",
    "wyłącznie sztywnych typu tarczowego",
    "wyłącznie samonastawnych typu kłowego"],c:1,
 e:"Większość sprzęgieł rozłącznych może pełnić rolę hamulca, gdy jeden z członów uczynimy nieruchomym."},
{t:"ham",q:"W szczękowym hamulcu bębnowym w układzie niesymetrycznym działanie obu szczęk jest:",
 a:["jednakowe (równe siły docisku obu szczęk)",
    "zawsze całkowicie wyłączone podczas hamowania",
    "zależne wyłącznie od temperatury okładzin",
    "niezależne od geometrii zamocowania przegubów"],c:0,
 e:"W układzie niesymetrycznym dobiera się geometrię tak, by działanie obu szczęk było jednakowe."},

/* ===================== PRZEKŁADNIE ZĘBATE ===================== */
{t:"przek",q:"Ogólna sprawność klasycznego układu napędowego (silnik–przekładnia–maszyna) wynosi:",
 a:["η = η₁ + η₂ + η₃, jako suma sprawności członów",
    "η = η₁ · η₂ · η₃, jako iloczyn sprawności członów",
    "η = η₁ / (η₂·η₃), jako iloraz sprawności",
    "η = η₁ − η₂ − η₃, jako różnica sprawności"],c:1,
 e:"Sprawności kolejnych członów mnożą się: η = η₁·η₂·η₃."},
{t:"przek",q:"Przełożenie kinematyczne, geometryczne i dynamiczne przekładni to odpowiednio:",
 a:["i = ω₁/ω₂; u = z₂/z₁; uη = M₂/M₁",
    "i = z₂/z₁; u = ω₁/ω₂; uη = M₁/M₂",
    "i = M₂/M₁; u = ω₁/ω₂; uη = z₂/z₁",
    "i = d₁/d₂; u = M₂/M₁; uη = ω₁/ω₂"],c:0,
 e:"i = ω₁/ω₂ = n₁/n₂ (kinematyczne); u = d₂/d₁ = z₂/z₁ (geometryczne); uη = M₂/M₁ (dynamiczne)."},
{t:"przek",q:"Przełożenie całkowite przekładni wielostopniowej wyznacza się jako:",
 a:["u = u₁ · u₂ · … · uₓ (iloczyn przełożeń stopni)",
    "u = u₁ + u₂ + … + uₓ (suma przełożeń stopni)",
    "u = u₁ / (u₂·…·uₓ) (iloraz przełożeń)",
    "u = (u₁ + uₓ)/2 (średnia przełożeń skrajnych)"],c:0,
 e:"Przełożenie całkowite to iloczyn przełożeń poszczególnych stopni: u = u₁·u₂·…·uₓ."},
{t:"przek",q:"Reduktor i multiplikator różnią się tym, że:",
 a:["reduktor ma i > 1 (zębnik czynny), multiplikator i < 1 (koło czynne)",
    "reduktor ma i < 1 (koło czynne), multiplikator i > 1 (zębnik czynny)",
    "oba mają i > 1, lecz różne kierunki obrotów",
    "oba mają i < 1, lecz różną liczbę stopni"],c:0,
 e:"Reduktor (i > 1) zmniejsza obroty, zwiększa moment — czynny jest zębnik; multiplikator (i < 1) przyspiesza — czynne jest koło."},
{t:"przek",q:"Zgodnie z klasyfikacją przekładnie mechaniczne dzielą się na:",
 a:["zębate, cięgnowe oraz cierne",
    "spoczynkowe, ruchowe oraz półruchowe",
    "sztywne, podatne oraz przegubowe",
    "klockowe, taśmowe oraz tarczowe"],c:0,
 e:"Podstawowy podział: przekładnie zębate, cięgnowe i cierne."},
{t:"przek",q:"Podstawowa odległość osi (zerowa) pary kół walcowych wynosi:",
 a:["a = (d₁ + d₂)/2 = (z₁ + z₂)·m/2",
    "a = (d₂ − d₁)/2 = (z₂ − z₁)·m/2",
    "a = d₁·d₂/2 = z₁·z₂·m/2",
    "a = (d₁ + d₂) = (z₁ + z₂)·m"],c:0,
 e:"Odległość osi a = (d₁ + d₂)/2 = (z₁ + z₂)·m/2 (m — moduł)."},
{t:"przek",q:"Średnicę podziałową oraz zasadniczą koła zębatego opisują zależności:",
 a:["d = z·m oraz d_b = d·cosα",
    "d = m/z oraz d_b = d/cosα",
    "d = z + m oraz d_b = d·sinα",
    "d = π·m oraz d_b = d·tgα"],c:0,
 e:"Średnica podziałowa d = z·m, a zasadnicza d_b = d·cosα (α — kąt zarysu)."},
{t:"przek",q:"Podstawowe prawo zazębienia wymaga, aby wspólna normalna w punkcie styku zębów:",
 a:["była zawsze prostopadła do osi obu wałów",
    "dzieliła odcinek O₁O₂ w stałym stosunku równym przełożeniu",
    "przechodziła dokładnie przez wierzchołek współpracującego zęba",
    "była styczna do okręgu wierzchołkowego większego koła"],c:1,
 e:"Wspólna normalna N–N musi dzielić odcinek O₁O₂ w stałym stosunku r_w2/r_w1 równym przełożeniu."},
{t:"przek",q:"Funkcja ewolwentowa (inwoluta) kąta α_Y ma postać:",
 a:["inv α_Y = tg α_Y − α_Y",
    "inv α_Y = α_Y − tg α_Y",
    "inv α_Y = tg α_Y + α_Y",
    "inv α_Y = sin α_Y − cos α_Y"],c:0,
 e:"Funkcja ewolwentowa: inv α_Y = tg α_Y − α_Y."},
{t:"przek",q:"Główną zaletą zarysu ewolwentowego zęba jest:",
 a:["całkowity brak nacisków stykowych Hertza",
    "mała wrażliwość na odchyłki odległości osi kół",
    "zerowy koszt wykonania kół tym zarysem",
    "wyeliminowanie potrzeby stosowania korekcji"],c:1,
 e:"Zarys ewolwentowy zapewnia stałe przełożenie kinematyczne nawet przy odchyłkach odległości osi."},
{t:"przek",q:"Wadą zazębienia zewnętrznego o zarysie ewolwentowym jest:",
 a:["niemożność doboru kół w dowolne pary",
    "całkowity brak ciągłości procesu zazębienia",
    "współpraca powierzchni wypukłych i duże naciski Hertza",
    "zbyt cicha praca utrudniająca diagnostykę słuchową"],c:2,
 e:"Przy zazębieniu zewnętrznym współpracują dwie powierzchnie wypukłe, co daje duże naciski stykowe Hertza."},
{t:"przek",q:"Wskaźnik zazębienia ε pary kół zębatych wyraża się jako:",
 a:["ε = ε₁ + ε₂ (suma wskaźników cząstkowych)",
    "ε = ε₁ · ε₂ (iloczyn wskaźników cząstkowych)",
    "ε = ε₁ − ε₂ (różnica wskaźników cząstkowych)",
    "ε = ε₁ / ε₂ (iloraz wskaźników cząstkowych)"],c:0,
 e:"Wskaźnik zazębienia ε = E₁E₂/p_b = ε₁ + ε₂ (suma cząstkowych); powinien być ε > 1."},
{t:"przek",q:"Graniczna liczba zębów dla kół walcowych (α = 20°, h*a = 1) wynosi teoretycznie:",
 a:["z_g = 5, praktycznie około 4",
    "z_g = 17, praktycznie około 14",
    "z_g = 30, praktycznie około 25",
    "z_g = 100, praktycznie około 90"],c:1,
 e:"Dla α = 20° teoretyczna graniczna liczba zębów z_g = 17 (praktycznie ok. 14); dla α = 15° z_g = 30 (25)."},
{t:"przek",q:"Podcięcie podstawy zęba w metodzie obwiedniowej następuje, gdy liczba zębów:",
 a:["jest mniejsza od granicznej (z < z_g)",
    "jest dokładnie równa granicznej (z = z_g)",
    "jest większa od granicznej (z > z_g)",
    "jest liczbą parzystą podzielną przez cztery"],c:0,
 e:"Podcięcie zachodzi przy z < z_g — miarodajna linia wierzchołków narzędzia przecina punkt G₁ okręgu zasadniczego."},
{t:"przek",q:"Grubość zęba na kole podziałowym z korekcją x·m wyraża się jako:",
 a:["s = (π/2 + 2x·tgα)·m",
    "s = (π/2 − 2x·tgα)·m",
    "s = (π/4 + x·tgα)·m",
    "s = π·m − x (bez kąta zarysu)"],c:0,
 e:"Grubość zęba z korekcją s = (π/2 + 2x·tgα)·m, gdzie przyrost Δs = 2x·m·tgα (dla x > 0 ząb grubszy)."},
{t:"przek",q:"Korekcja zerowa (P-0) charakteryzuje się tym, że:",
 a:["x₁ = x₂ i odległość osi wyraźnie rośnie",
    "x₁ = −x₂ i odległość osi nie ulega zmianie",
    "stosuje się ją wyłącznie w przekładniach ślimakowych",
    "zawsze powoduje podcięcie podstawy zęba"],c:1,
 e:"W korekcji zerowej P-0 x₁ = −x₂, więc odległość osi pozostaje niezmieniona; warunek: z₁ + z₂ ≥ 2z_g."},
{t:"przek",q:"Prędkość obwodową v oraz prędkość kątową ω koła wyznacza się ze wzorów:",
 a:["v = π·d·n/60 oraz ω = 2π·n/60",
    "v = 60/(π·d·n) oraz ω = 60/(2π·n)",
    "v = π·d·n oraz ω = 2π·n",
    "v = d·n/60 oraz ω = π·n/60"],c:0,
 e:"Prędkość obwodowa v = π·d·n/60 [m/s], a prędkość kątowa ω = 2π·n/60 [rad/s]."},
{t:"przek",q:"Według kształtu linii zęba przekładnie zębate dzieli się na zęby:",
 a:["proste, skośne, strzałkowe oraz łukowe",
    "statyczne, dynamiczne oraz udarowe",
    "osiowe, promieniowe oraz wichrowate",
    "twarde, miękkie oraz ulepszane cieplnie"],c:0,
 e:"Według linii zęba: proste, skośne, strzałkowe i łukowe."},
{t:"przek",q:"W przekładni stożkowej hipoidalnej, w odróżnieniu od stożkowej czołowej:",
 a:["oś zębnika jest przesunięta względem osi koła talerzowego",
    "sprawność osiąga dokładnie 100% niezależnie od obciążenia",
    "koła muszą leżeć dokładnie na jednej wspólnej osi",
    "w ogóle nie występuje zazębienie współpracujących kół"],c:0,
 e:"W przekładni hipoidalnej oś zębnika jest przesunięta — daje to większą wytrzymałość i lepszą płynność zazębienia."},
{t:"przek",q:"Para koło zębate–zębatka prosta (listwa) służy do:",
 a:["zamiany ruchu obrotowego na postępowy i odwrotnie",
    "nieograniczonego zwiększania momentu skręcającego",
    "tłumienia drgań skrętnych w układzie napędowym",
    "hamowania obracającego się bębna hamulcowego"],c:0,
 e:"Para koło–zębatka zamienia ruch obrotowy na postępowy (i odwrotnie); listwa to koło o promieniu → ∞."},
{t:"przek",q:"Do przekładni cięgnowych (a nie zębatych) zalicza się przekładnie:",
 a:["czołowe oraz śrubowe walcowe",
    "pasowe, linowe oraz łańcuchowe",
    "walcowe oraz stożkowe hipoidalne",
    "planetarne oraz ślimakowe globoidalne"],c:1,
 e:"Przekładnie cięgnowe to: pasowe, linowe i łańcuchowe; zębate dzielą się na czołowe i śrubowe."},
];
