/* Baza pytań quizu PKM II.
 * Każde pytanie: {t: temat, q: treść, a: [4 odpowiedzi], c: indeks poprawnej (0-3), e: wyjaśnienie}
 * Odpowiedzi są celowo zbliżonej długości — poprawna nie jest możliwa do "odgadnięcia po długości".
 */
window.TOPICS = {
  gwint: {name: "Połączenia gwintowe", ico: "\uD83D\uDD29"},
  spaw:  {name: "Połączenia spawane",  ico: "\uD83D\uDD25"},
  sprz:  {name: "Sprzęgła",            ico: "\u2699\uFE0F"},
  ham:   {name: "Hamulce",             ico: "\uD83D\uDED1"},
  przek: {name: "Przekładnie zębate",  ico: "\uD83E\uDDB7"},
};

window.QUESTIONS = [
/* ===================== POŁĄCZENIA GWINTOWE ===================== */
{t:"gwint",q:"Co określa wielkość p_dop (k_d) w połączeniach gwintowych?",
 a:["dopuszczalny nacisk powierzchniowy współpracujących zwojów gwintu",
    "dopuszczalne naprężenie rozciągające występujące w rdzeniu śruby",
    "moment skręcający niezbędny do prawidłowego dokręcenia nakrętki",
    "graniczną wartość współczynnika tarcia w pracującej parze gwintowej"],c:0,
 e:"p_dop (k_d) to dopuszczalny nacisk powierzchniowy między zwojami; zależy od materiału i rodzaju połączenia."},
{t:"gwint",q:"Najwyższe dopuszczalne naciski k_d występują w połączeniach:",
 a:["ruchowych, pracujących stale w przekładniach śrubowych",
    "spoczynkowych, łączonych na stałe elementami złącznymi",
    "półruchowych, poruszanych jedynie sporadycznie w pracy",
    "dociskowych, obciążanych jednocześnie udarowo i cieplnie"],c:1,
 e:"Połączenia spoczynkowe dopuszczają najwyższe naciski; ruchowe (przekładnie) mają wartości najniższe."},
{t:"gwint",q:"Jaką wysokość nakrętki m przyjmuje się dla normalnych łączników spoczynkowych?",
 a:["m = 0,3d, gdyż wystarczają trzy czynne zwoje gwintu",
    "m = 2,5d, aby maksymalnie odciążyć pierwszy zwój",
    "m = 0,8d, przyjmowaną zwykle bez dodatkowych obliczeń",
    "m = 1,5d, ze względu na duże naciski na zwojach"],c:2,
 e:"Dla normalnych łączników spoczynkowych przyjmuje się m = 0,8d (bez obliczeń sprawdzających)."},
{t:"gwint",q:"Jaką wysokość nakrętki przyjmuje się dla połączeń ruchowych?",
 a:["m = (0,2 ÷ 0,4)d, bo zwoje są słabo obciążone",
    "m = (1,5 ÷ 2,0)d, z uwagi na większe naciski zwojów",
    "m = (0,6 ÷ 0,8)d, identycznie jak dla spoczynkowych",
    "m = (3,0 ÷ 4,0)d, aby wyrównać rozkład obciążenia"],c:1,
 e:"Połączenia ruchowe są bardziej obciążone, więc nakrętki są wyższe: m = (1,5 ÷ 2,0)d."},
{t:"gwint",q:"Typowym przykładem śruby obciążonej wyłącznie siłą osiową jest:",
 a:["śruba pociągowa tokarki przesuwająca suport",
    "śruba podnośnika samochodowego (napędowa)",
    "hak dźwigowy zawieszony na cięgnie z gwintem",
    "śruba mocująca koło pasowe na czopie wału"],c:2,
 e:"Hak dźwigowy przenosi tylko siłę osiową (rozciąganie) – brak momentu skręcającego."},
{t:"gwint",q:"Śruba podnośnikowa (napędowa) jest przykładem śruby obciążonej:",
 a:["wyłącznie siłą poprzeczną ścinającą rdzeń",
    "jedynie momentem gnącym od mimośrodu",
    "wyłącznie wyboczeniem występującym przy długim smukłym trzpieniu",
    "siłą osiową oraz momentem skręcającym jednocześnie"],c:3,
 e:"W śrubie napędowej rdzeń jest rozciągany/ściskany siłą osiową i jednocześnie skręcany momentem."},
{t:"gwint",q:"Długie śruby ściskane należy dodatkowo sprawdzić na:",
 a:["wyboczenie, czyli spełnienie warunku stateczności",
    "naciski dopuszczalne na współpracujących zwojach",
    "szczelność, aby zapewnić brak przecieków złącza",
    "zmęczenie cieplne wynikające z nagrzewania rdzenia"],c:0,
 e:"Smukłe śruby ściskane mogą stracić stateczność, dlatego sprawdza się je dodatkowo na wyboczenie."},
{t:"gwint",q:"Wzór Eulera na naprężenie krytyczne stosuje się przy wyboczeniu:",
 a:["sprężysto-plastycznym, gdy smukłość λ < λgr",
    "sprężystym, gdy smukłość λ jest większa lub równa λgr",
    "wyłącznie statycznym, niezależnie od smukłości pręta",
    "wyłącznie zmęczeniowym przy obciążeniach zmiennych"],c:1,
 e:"Wzór Eulera (σkr = π²E/λ²) obowiązuje w zakresie sprężystym, czyli dla λ ≥ λgr."},
{t:"gwint",q:"Wzór Tetmajera opisuje zakres wyboczenia:",
 a:["sprężysty, gdy smukłość λ przekracza λgr",
    "wyłącznie statyczny przy stałym obciążeniu",
    "sprężysto-plastyczny, gdy smukłość λ < λgr",
    "zmęczeniowy przy obciążeniach cyklicznych"],c:2,
 e:"Wzór Tetmajera (σkr = σo − bλ) obowiązuje w zakresie sprężysto-plastycznym, dla λ < λgr."},
{t:"gwint",q:"O charakterze wyboczenia śruby (sprężyste czy niesprężyste) decyduje:",
 a:["rodzaj materiału użytego na nakrętkę śruby",
    "wartość skoku gwintu oraz jego krotność",
    "temperatura otoczenia podczas pracy złącza",
    "smukłość λ śruby oraz sposób jej zamocowania"],c:3,
 e:"Charakter wyboczenia zależy od smukłości λ i sposobu zamocowania (a nie od materiału nakrętki czy skoku)."},
{t:"gwint",q:"Optymalnym, najkorzystniejszym obciążeniem śruby jest obciążenie:",
 a:["momentem gnącym od nierównoległych powierzchni",
    "siłą osiową działającą wzdłuż osi śruby",
    "siłą poprzeczną ścinającą trzpień śruby",
    "obciążeniem cieplnym od nagrzewania złącza"],c:1,
 e:"Najkorzystniejsze jest czyste obciążenie siłą osiową – wymaga prostopadłości powierzchni oporowej."},
{t:"gwint",q:"Dodatkowe naprężenia gnące w śrubie (od nieprostopadłości oparcia):",
 a:["znacznie obniżają nośność zmęczeniową śruby",
    "wyraźnie zwiększają trwałość zmęczeniową złącza",
    "nie mają żadnego wpływu na pracę połączenia",
    "występują tylko przy czystym ściskaniu rdzenia"],c:0,
 e:"Naprężenia gnące sumują się z osiowymi i znacznie obniżają nośność zmęczeniową śruby."},
{t:"gwint",q:"Aby zmniejszyć ugięcie i naprężenia gnące, śruba powinna być:",
 a:["możliwie krótka i sztywna, o małej smukłości",
    "wykonana z żeliwa szarego zamiast ze stali stopowej konstrukcyjnej",
    "bardziej elastyczna i smukła, o dużym stosunku l/dr",
    "o znacznie powiększonej średnicy rdzenia dr"],c:2,
 e:"Im większy stosunek l/dr (śruba smuklejsza, podatniejsza), tym mniejsze naprężenia gnące."},
{t:"gwint",q:"Ile stanów rozróżnia się przy analizie śruby napiętej wstępnie?",
 a:["trzy: zimny, ciepły oraz gorący",
    "trzy: jałowy, częściowy oraz pełny",
    "trzy: początkowy, montażowy oraz roboczy",
    "trzy: pierwszego, drugiego i trzeciego biegu"],c:2,
 e:"Analizuje się stan początkowy (bez napięcia), montażowy (napięcie wstępne) i roboczy (z siłą Q)."},
{t:"gwint",q:"Współczynnik χ w złączu śrubowym napiętym wstępnie to:",
 a:["współczynnik obciążenia złącza śrubowego",
    "współczynnik tarcia w gwincie nakrętki",
    "smukłość graniczna materiału śruby",
    "sprawność energetyczna połączenia gwintowego"],c:0,
 e:"χ to współczynnik obciążenia złącza – określa, jaka część siły zewnętrznej dociąża śrubę."},
{t:"gwint",q:"Zacisk resztkowy kołnierzy Qz dobiera się tak, aby:",
 a:["zminimalizować masę zastosowanej śruby",
    "zapewnić szczelność wykonanego połączenia",
    "zwiększyć skok gwintu współpracującej nakrętki",
    "całkowicie wyeliminować tarcie między zwojami"],c:1,
 e:"Zacisk resztkowy Qz musi pozostać dodatni, by kołnierze były dociśnięte i połączenie było szczelne."},
{t:"gwint",q:"Współczynnik swobodnej długości μw przy wyboczeniu zależy od:",
 a:["materiału, z którego wykonano nakrętkę",
    "wartości skoku gwintu współpracującej śruby",
    "temperatury panującej w otoczeniu złącza",
    "sposobu zamocowania (utwierdzenia) końców śruby"],c:3,
 e:"μw zależy wyłącznie od warunków podparcia/utwierdzenia śruby (przypadki Eulera I–VI)."},
{t:"gwint",q:"Warunek wytrzymałościowy śruby obciążonej siłą osiową dotyczy:",
 a:["naprężeń ścinających powstających w gwincie",
    "naprężeń rozciągających występujących w rdzeniu",
    "nacisków powierzchniowych na czołach zwojów",
    "momentu skręcającego działającego na trzpień"],c:1,
 e:"Śrubę obciążoną siłą osiową sprawdza się na naprężenia rozciągające w przekroju rdzenia (dr)."},

/* ===================== POŁĄCZENIA SPAWANE ===================== */
{t:"spaw",q:"Połączenie spawane zalicza się do połączeń:",
 a:["rozłącznych, możliwych do wielokrotnego montażu",
    "nierozłącznych, niemożliwych do rozdzielenia bez zniszczenia",
    "spoczynkowych, poruszanych jedynie podczas okresowej regulacji ustawienia",
    "ciernych, przenoszących obciążenie siłą docisku"],c:1,
 e:"Spawanie daje połączenie nierozłączne – rozdzielenie wymaga zniszczenia spoiny."},
{t:"spaw",q:"Spoina w złączu spawanym powstaje w wyniku:",
 a:["dokręcenia śrub łączących elementy konstrukcji",
    "sprasowania powierzchni na zimno pod dużym naciskiem",
    "stopienia i krzepnięcia stopiwa oraz materiałów rodzimych",
    "naniesienia warstwy kleju konstrukcyjnego między elementy"],c:2,
 e:"Spoina powstaje przez stopienie i zakrzepnięcie stopiwa (dodatkowego) oraz materiałów rodzimych."},
{t:"spaw",q:"Spoinami czołowymi łączy się elementy:",
 a:["nasunięte na siebie i połączone przez otwory",
    "dosunięte do siebie czołami i wypełnione spoiną",
    "nachylone względem siebie, wypełniając ich kąt",
    "rozsunięte i opasane wspólnym cięgnem nośnym"],c:1,
 e:"Spoiny czołowe łączą elementy dosunięte czołami; rowek może mieć różny kształt (I, V, X...)."},
{t:"spaw",q:"Kształt rowka spoiny czołowej przypomina wielkie litery:",
 a:["A, B, C oraz D",
    "L, M, N oraz T",
    "O, P, Q oraz R",
    "I, V, Y, X, U, J, K"],c:3,
 e:"Zarys rowka spoiny czołowej wskazuje podobieństwo do liter I, V, Y, X, U, J, K."},
{t:"spaw",q:"Spoina pachwinowa ma w przekroju poprzecznym kształt:",
 a:["trójkąta równoramiennego",
    "wycinka koła o dużym promieniu",
    "prostokąta o znacznej wysokości",
    "trapezu równoramiennego"],c:0,
 e:"Spoina pachwinowa ma w przekroju kształt trójkąta równoramiennego."},
{t:"spaw",q:"Spoinami otworowymi łączy się elementy:",
 a:["dosunięte do siebie czołami płaszczyzn",
    "nachylone względem siebie pod kątem prostym",
    "nasunięte na siebie, z otworami wypełnionymi spoiną",
    "rozsunięte i opasane wspólnym cięgnem stalowym"],c:2,
 e:"W spoinie otworowej w jednym z nasuniętych elementów wykonuje się otwory wypełniane spoiną."},
{t:"spaw",q:"We wzorze k' = z₀·z·k_r wielkość z₀ oznacza:",
 a:["współczynnik jakości wykonanej spoiny",
    "współczynnik wytrzymałości statycznej",
    "liczbę spoin w analizowanym połączeniu",
    "naprężenie dopuszczalne materiału rodzimego"],c:1,
 e:"z₀ to współczynnik wytrzymałości statycznej (np. 0,75 dla rozciągania, 0,65 dla ścinania)."},
{t:"spaw",q:"Współczynnik jakości spoiny z (0,5 ÷ 1,0) zależy od:",
 a:["temperatury otoczenia podczas eksploatacji",
    "barwy powłoki ochronnej naniesionej na spoinę",
    "konstrukcji oraz staranności wykonania spoiny",
    "wyłącznie od prędkości prowadzenia łuku"],c:2,
 e:"Współczynnik z zależy od konstrukcji złącza i staranności wykonania spoiny (kontrola, defektoskopia)."},
{t:"spaw",q:"Skrót SWC w połączeniu spawanym oznacza:",
 a:["strefę wpływu ciepła wokół spoiny",
    "standardowy współczynnik ciągliwości stali",
    "stan wytrzymałości chwilowej materiału",
    "spoinę współczynnikową typu czołowego"],c:0,
 e:"SWC to strefa wpływu ciepła – obszar materiału rodzimego o zmienionej strukturze obok spoiny."},
{t:"spaw",q:"Wg Eurokodu 3 efektywną grubość spoiny pachwinowej a przyjmuje się jako:",
 a:["pełną szerokość łączonego elementu",
    "grubość cieńszego z łączonych elementów",
    "całkowitą długość lica wykonanej spoiny wzdłuż całego złącza",
    "wysokość największego trójkąta wpisanego w przekrój"],c:3,
 e:"Grubość obliczeniowa a to wysokość największego trójkąta wpisanego w przekrój spoiny."},
{t:"spaw",q:"Minimum technologiczne grubości spoiny pachwinowej wg Eurokodu 3 wynosi:",
 a:["a ≥ 1 mm, dla zachowania ciągłości lica",
    "a ≥ 3 mm, dla zapewnienia stabilności łuku",
    "a ≥ 10 mm, dla przeniesienia obciążeń",
    "a ≥ 0,5 mm, dla cienkich blach poszycia"],c:1,
 e:"Minimum technologiczne to a ≥ 3 mm – poniżej trudno utrzymać stabilny łuk spawalniczy."},
{t:"spaw",q:"Sprężysto-plastyczny stan odkształceń w spoinie:",
 a:["jest dopuszczalny statycznie, lecz niepożądany zmęczeniowo",
    "jest zawsze całkowicie niedopuszczalny w każdym rodzaju złącza spawanego",
    "występuje wyłącznie w spoinach typu otworowego",
    "zawsze zwiększa trwałość zmęczeniową połączenia"],c:0,
 e:"Przy obciążeniach statycznych jest akceptowalny, ale przy zmiennych obniża trwałość zmęczeniową."},
{t:"spaw",q:"Zasadniczym elementem nośnym złącza spawanego jest:",
 a:["nit osadzany w otworze elementu",
    "spoina łącząca materiały rodzime",
    "nakrętka dociskająca powierzchnie",
    "kołek ustalający wzajemne położenie"],c:1,
 e:"Nośnym elementem złącza spawanego jest spoina, powstała ze stopiwa i materiału rodzimego."},

/* ===================== SPRZĘGŁA ===================== */
{t:"sprz",q:"Sprzęgło to zespół służący do:",
 a:["trwałej zmiany kierunku momentu obrotowego wału",
    "hamowania i zatrzymywania ruchomego członu maszyny",
    "łączenia wałów i przenoszenia momentu bez trwałej jego zmiany",
    "zmiany prędkości kątowej oraz wartości przenoszonego momentu obrotowego"],c:2,
 e:"Sprzęgło łączy wały i przenosi moment obrotowy bez trwałej zmiany jego wartości i kierunku."},
{t:"sprz",q:"Z jakich podstawowych członów składa się sprzęgło?",
 a:["z członu czynnego, członu biernego oraz łącznika",
    "z tłoka, korbowodu oraz wału korbowego silnika",
    "z bębna, szczęki hamulcowej oraz okładziny ciernej",
    "z zębnika, koła zębatego oraz wałka pośredniego"],c:0,
 e:"Sprzęgło tworzą: człon czynny (napędzający), człon bierny (napędzany) i łącznik."},
{t:"sprz",q:"Który z poniższych NIE jest rodzajem łącznika w sprzęgle?",
 a:["łącznik wykorzystujący ciało stałe (mechaniczny)",
    "łącznik wykorzystujący strumień światła (optyczny)",
    "łącznik wykorzystujący siły pola elektromagnetycznego",
    "łącznik wykorzystujący ciecz (hydrodynamiczny)"],c:1,
 e:"Łączniki dzielą się na mechaniczne, elektromagnetyczne i hydrodynamiczne – nie ma optycznych."},
{t:"sprz",q:"Przemieszczenia względne łączonych wałów dzieli się na:",
 a:["pionowe, poziome oraz skośne",
    "statyczne, dynamiczne oraz cieplne",
    "osiowe, promieniowe oraz kątowe",
    "sprężyste, plastyczne oraz lepkie"],c:2,
 e:"Niewspółosiowość wałów może być osiowa, promieniowa lub kątowa."},
{t:"sprz",q:"Współczynnik przeciążenia K wiąże moment maksymalny z nominalnym wzorem:",
 a:["Mmax = K + M",
    "Mmax = M / K",
    "Mmax = K² · M",
    "Mmax = K · M"],c:3,
 e:"Moment maksymalny uwzględnia nadwyżkę dynamiczną: Mmax = K · M."},
{t:"sprz",q:"Do sprzęgieł nierozłącznych mechanicznych zalicza się sprzęgła:",
 a:["sztywne, samonastawne oraz podatne",
    "cierne oraz sterowane elektromagnetycznie",
    "odśrodkowe oraz przeciążeniowe (bezpieczeństwa)",
    "hydrodynamiczne oraz synchroniczne kształtowe"],c:0,
 e:"Sprzęgła nierozłączne mechaniczne to: sztywne, samonastawne i podatne."},
{t:"sprz",q:"Sprzęgła nierozłączne to takie, w których:",
 a:["można je swobodnie rozłączyć w dowolnej chwili pracy",
    "moment przenoszony jest wyłącznie siłą tarcia okładzin",
    "po przeciążeniu następuje samoczynne rozłączenie wałów",
    "człony połączone są trwale, rozłączane tylko przy demontażu"],c:3,
 e:"W sprzęgłach nierozłącznych człony łączy się trwale; rozłączenie tylko podczas demontażu maszyny."},
{t:"sprz",q:"Sprzęgła sztywne wymagają od łączonych wałów:",
 a:["zachowania dokładnej współosiowości",
    "dużej, zamierzonej niewspółosiowości",
    "stale zmiennego kąta przekoszenia osi",
    "wywoływania znacznych drgań skrętnych"],c:0,
 e:"Sprzęgła sztywne nie kompensują błędów ustawienia – wymagają współosiowości wałów."},
{t:"sprz",q:"Sprzęgła samonastawne umożliwiają łączenie wałów:",
 a:["wyłącznie idealnie współosiowych względem siebie",
    "przy niewielkich zmianach względnego położenia osi",
    "przy dużych, zamierzonych zmianach kąta przekoszenia",
    "stosowanych jedynie w napędach hydraulicznych"],c:1,
 e:"Sprzęgła samonastawne kompensują niewielkie błędy ustawienia osi (montaż, odkształcenia)."},
{t:"sprz",q:"Sprzęgła podatne stosuje się głównie, gdy w układzie:",
 a:["występują duże drgania wymagające tłumienia",
    "panują wyłącznie obciążenia czysto statyczne",
    "występują bardzo małe prędkości obrotowe",
    "w ogóle nie jest przenoszony moment obrotowy"],c:0,
 e:"Sprzęgła podatne (z wkładką elastyczną) tłumią drgania skrętne i łagodzą udary."},
{t:"sprz",q:"Zamierzone zmiany położenia kątowego wałów realizuje się sprzęgłami:",
 a:["sztywnymi tarczowymi o sztywnym kołnierzu",
    "ciernymi wielopłytkowymi z dociskiem sprężyn",
    "przegubowymi (Cardana) o ruchomych widełkach",
    "odśrodkowymi z elementami dociskanymi siłą"],c:2,
 e:"Sprzęgła przegubowe (Cardana) pozwalają na pracę przy zmiennym kącie między osiami wałów."},
{t:"sprz",q:"Pojedyncze sprzęgło przegubowe (Cardana) przenosi ruch:",
 a:["zawsze idealnie jednostajnie i bez wahań",
    "tylko przy pełnej współosiowości obu łączonych wałów napędowych",
    "bez przenoszenia jakiegokolwiek momentu",
    "niejednostajnie – ze zmienną prędkością wału biernego"],c:3,
 e:"Pojedynczy przegub Cardana daje niejednostajny bieg wału biernego (zmienna ωβ)."},
{t:"sprz",q:"Podwójne sprzęgło przegubowe z wałkiem pośrednim pozwala na:",
 a:["zwiększenie niejednostajności biegu napędzanej maszyny roboczej",
    "całkowitą eliminację przenoszonego momentu",
    "synchronizację prędkości kątowych i jednostajny bieg",
    "zamianę ruchu obrotowego na ruch postępowy"],c:2,
 e:"Podwójny przegub (przy równych kątach) synchronizuje prędkości – maszyna pracuje jednostajnie."},
{t:"sprz",q:"W sprzęgłach ciernych moment obrotowy przenoszony jest przez:",
 a:["tarcie, przy warunku M_T ≥ K · M",
    "zazębienie współpracujących kół zębatych",
    "oddziaływanie pola elektromagnetycznego",
    "krążący strumień cieczy roboczej"],c:0,
 e:"W sprzęgłach ciernych moment przenosi tarcie; musi być spełniony warunek M_T ≥ K·M."},
{t:"sprz",q:"Do sprzęgieł samoczynnych zalicza się sprzęgła:",
 a:["sztywne, podatne oraz samonastawne",
    "synchroniczne oraz kształtowe zębate",
    "przegubowe oraz teleskopowo-przegubowe z ruchomym wałkiem",
    "bezpieczeństwa, jednokierunkowe oraz odśrodkowe"],c:3,
 e:"Sprzęgła samoczynne to: bezpieczeństwa (przeciążeniowe), jednokierunkowe i odśrodkowe."},
{t:"sprz",q:"Sprzęgło bezpieczeństwa (np. kulkowe, wielopłytkowe) działa tak, że:",
 a:["po przeciążeniu następuje poślizg i spadek momentu",
    "po przeciążeniu trwale i nieodwracalnie blokuje wały",
    "wraz ze wzrostem obciążenia zwiększa moment",
    "samoczynnie zmienia kierunek obrotów wału"],c:0,
 e:"Po przekroczeniu momentu granicznego sprzęgło bezpieczeństwa ślizga się, ograniczając moment."},
{t:"sprz",q:"Niemiecka norma DIN 740-2 dotyczy przede wszystkim:",
 a:["obliczania spoin pachwinowych konstrukcji",
    "doboru i wymiarowania sprzęgieł podatnych",
    "doboru łożysk tocznych w węzłach wałów",
    "geometrii zazębienia kół zębatych walcowych"],c:1,
 e:"DIN 740-2 to powszechna w Europie norma doboru i wymiarowania sprzęgieł podatnych."},
{t:"sprz",q:"O wyborze rodzaju sprzęgła (np. cierne czy synchroniczne) decyduje głównie:",
 a:["barwa obudowy zastosowanego sprzęgła",
    "masa nakrętek mocujących sprzęgło",
    "różnica prędkości łączonych wałów",
    "liczba zębów koła napędzanego"],c:2,
 e:"Przy dużej różnicy prędkości stosuje się sprzęgła cierne, przy małej – synchroniczne (kształtowe)."},
{t:"sprz",q:"Nominalny moment obrotowy przenoszony przez sprzęgło wyznacza wzór:",
 a:["M = z · m, gdzie z to liczba zębów",
    "M = N · ω², gdzie ω to prędkość kątowa",
    "M = ω / N, gdzie N oznacza moc",
    "M = N / ω, gdzie N to moc, ω prędkość kątowa"],c:3,
 e:"Moment dobiera się z mocy i prędkości: M = N/ω (lub M = 9550·N/n)."},

/* ===================== HAMULCE ===================== */
{t:"ham",q:"Hamulce są elementami układu napędowego służącymi do:",
 a:["zatrzymania, regulacji prędkości lub utrzymania położenia",
    "zwiększania momentu obrotowego przenoszonego przez wał",
    "zmiany przełożenia geometrycznego w układzie napędowym",
    "smarowania współpracujących łożysk i powierzchni ślizgowych"],c:0,
 e:"Hamulce służą do zatrzymania, regulacji prędkości lub utrzymania układu w stałym położeniu."},
{t:"ham",q:"Zadanie hamowania realizowane jest przez:",
 a:[    "zazębienie współpracujących walcowych kół zębatych przekładni",
    "pole magnetyczne wytwarzane wokół wału",
    "sprzężenie cierne członu ruchomego z nieruchomym",
    "przepływ cieczy chłodzącej przez układ"],c:2,
 e:"Hamowanie realizuje sprzężenie cierne członu poruszającego się z członem nieruchomym."},
{t:"ham",q:"Podstawowa różnica między hamulcem a sprzęgłem polega na tym, że w hamulcu:",
 a:["oba człony swobodnie obracają się względem siebie",
    "jeden z członów połączony jest z elementem nieruchomym",
    "nie występuje w ogóle zjawisko tarcia okładzin",
    "przenoszony moment jest zawsze znacznie większy"],c:1,
 e:"W hamulcu jeden człon jest nieruchomy; w sprzęgle oba człony mogą się obracać."},
{t:"ham",q:"Który podział hamulców stosowanych w napędach jest poprawny?",
 a:["sztywne, podatne oraz cierne samonastawne",
    "czołowe, śrubowe oraz ślimakowe walcowe",
    "osiowe, promieniowe oraz kątowe przegubowe",
    "klockowe, szczękowe, tarczowe oraz taśmowe"],c:3,
 e:"Hamulce dzielą się na klockowe, szczękowe, tarczowe i taśmowe."},
{t:"ham",q:"Hamulce szczękowe (bębnowe) stosuje się najczęściej w:",
 a:["pojazdach samochodowych i motocyklach",
    "precyzyjnych mechanizmach zegarowych",
    "wirnikowych pompach przemysłowych",
    "liniach przesyłowych energii elektrycznej"],c:0,
 e:"Hamulce szczękowe (bębnowe) stosuje się głównie w pojazdach (samochody, motocykle)."},
{t:"ham",q:"Hamulce klockowe (jedno- i dwuklockowe) stosuje się głównie w:",
 a:["wyłącznie w precyzyjnych mechanizmach zegarków",
    "wyłącznie w przekładniach ślimakowych dużej mocy",
    "maszynach ogólnego przeznaczenia, dźwignicach, kolejkach",
    "wyłącznie w sprzęgłach hydrodynamicznych pojazdów ciężarowych"],c:2,
 e:"Hamulce klockowe stosuje się w maszynach ogólnego przeznaczenia, dźwignicach, kolejkach górskich."},
{t:"ham",q:"W hamulcu taśmowym wartość siły naciągu taśmy opisuje wzór:",
 a:["S₁ = S₂ + μα, jako suma składowych naciągu",
    "S₁ = S₂ · e^(μα), zgodnie ze wzorem Eulera",
    "S₁ = S₂ / μ, jako iloraz przez współczynnik tarcia",
    "S₁ = μ · N · R, jako iloczyn siły i promienia"],c:1,
 e:"Naciąg taśmy zmienia się wykładniczo wg wzoru Eulera: S₁ = S₂·e^(μα)."},
{t:"ham",q:"Rolę hamulca może spełniać większość sprzęgieł:",
 a:["nierozłącznych, połączonych trwale",
    "wyłącznie sztywnych tarczowych",
    "rozłącznych, dających się rozłączyć",
    "wyłącznie samonastawnych kłowych"],c:2,
 e:"Większość sprzęgieł rozłącznych może pełnić rolę hamulca (gdy jeden człon jest nieruchomy)."},
{t:"ham",q:"Hamulec taśmowy różnicowy przy niewłaściwym doborze parametrów działa jak:",
 a:["sprzęgło synchroniczne kształtowe",
    "bezstopniowy wariator pasowy",
    "multiplikator przyspieszający obroty",
    "zapadka blokująca obrót w jedną stronę"],c:3,
 e:"Przy a₂ ≤ a₁·e^(μα) hamulec różnicowy samoblokuje się i działa jak zapadka."},
{t:"ham",q:"Hamulce taśmowe stosuje się przede wszystkim jako:",
 a:["hamulce pomocnicze oraz postojowe",
    "główne hamulce robocze obrabiarek",
    "sprzęgła rozruchowe dużych silników",
    "elementy uszczelniające wały obrotowe"],c:0,
 e:"Hamulce taśmowe wykorzystuje się głównie jako pomocnicze i postojowe (np. kolejki górskie)."},

/* ===================== PRZEKŁADNIE ZĘBATE ===================== */
{t:"przek",q:"Przekładnia to mechanizm służący do przenoszenia ruchu obrotowego ze zmianą:",
 a:["prędkości kątowej ω oraz momentu obrotowego M",
    "wyłącznie temperatury współpracujących elementów",
    "jedynie kierunku działania siły osiowej w wale",
    "wyłącznie skoku gwintu na wale napędzającym"],c:0,
 e:"Przekładnia przenosi ruch obrotowy, zmieniając prędkość kątową ω i moment obrotowy M."},
{t:"przek",q:"Ogólna sprawność układu silnik–przekładnia–maszyna wynosi:",
 a:["η = η₁ + η₂ + η₃",
    "η = η₁ − η₂ − η₃",
    "η = η₁ · η₂ · η₃",
    "η = η₁ / η₂ / η₃"],c:2,
 e:"Sprawności poszczególnych członów mnożą się: η = η₁·η₂·η₃."},
{t:"przek",q:"Przełożenie kinematyczne i definiuje się jako:",
 a:["stosunek prędkości kątowych: i = ω₁/ω₂ = n₁/n₂",
    "stosunek średnic podziałowych: i = d₂/d₁",
    "iloczyn momentów obrotowych obu wałów",
    "sumę liczby zębów obu współpracujących kół"],c:0,
 e:"Przełożenie kinematyczne to stosunek prędkości: i = ω₁/ω₂ = n₁/n₂."},
{t:"przek",q:"Przełożenie geometryczne u definiuje się jako:",
 a:["u = M₂/M₁, czyli stosunek momentów",
    "u = d₂/d₁ = z₂/z₁, czyli stosunek średnic i zębów",
    "u = ω₁/ω₂, czyli stosunek prędkości kątowych",
    "u = π·m, czyli iloczyn modułu i liczby π"],c:1,
 e:"Przełożenie geometryczne to stosunek średnic (lub liczby zębów): u = d₂/d₁ = z₂/z₁."},
{t:"przek",q:"Reduktor to przekładnia, w której:",
 a:["i < 1, następuje wzrost liczby obrotów wału",
    "ani prędkość, ani moment nie ulegają zmianie",
    "koło duże jest zawsze elementem napędzającym",
    "i > 1, następuje redukcja obrotów i wzrost momentu"],c:3,
 e:"Reduktor (i > 1) zmniejsza obroty i zwiększa moment; kołem czynnym jest zębnik."},
{t:"przek",q:"Multiplikator to przekładnia, w której:",
 a:["i > 1 i następuje redukcja liczby obrotów",
    "i < 1 i następuje przyspieszenie (wzrost obrotów)",
    "moment obrotowy rośnie w sposób nieograniczony",
    "zębnik jest zawsze elementem napędzanym (biernym)"],c:1,
 e:"Multiplikator (i < 1) zwiększa obroty; kołem czynnym jest koło duże."},
{t:"przek",q:"Przekładnie mechaniczne dzielą się na:",
 a:["zębate, cięgnowe oraz cierne",
    "spoczynkowe, ruchowe oraz półruchowe",
    "sztywne, podatne oraz przegubowe",
    "klockowe, taśmowe oraz tarczowe"],c:0,
 e:"Podstawowy podział przekładni: zębate, cięgnowe i cierne."},
{t:"przek",q:"Do przekładni cięgnowych zalicza się przekładnie:",
 a:["czołowe oraz śrubowe walcowe",
    "walcowe oraz stożkowe hipoidalne",
    "pasowe, linowe oraz łańcuchowe",
    "planetarne oraz ślimakowe globoidalne"],c:2,
 e:"Przekładnie cięgnowe to: pasowe, linowe i łańcuchowe."},
{t:"przek",q:"Zębnikiem nazywamy:",
 a:["koło o mniejszej liczbie zębów (zwykle czynne)",
    "koło o większej liczbie zębów (zwykle bierne)",
    "wałek pośredni łączący dwa stopnie przekładni",
    "zewnętrzną obudowę mieszczącą koła zębate"],c:0,
 e:"Zębnik to koło mniejsze (o mniejszej liczbie zębów), zwykle napędzające."},
{t:"przek",q:"Ze względu na kształt linii zęba przekładnie dzielimy na zęby:",
 a:["statyczne, dynamiczne oraz udarowe",
    "proste, skośne, strzałkowe oraz łukowe",
    "osiowe, promieniowe oraz wichrowate",
    "twarde, miękkie oraz ulepszane cieplnie"],c:1,
 e:"Według linii zęba: proste, skośne, strzałkowe i łukowe."},
{t:"przek",q:"Wśród zalet przekładni zębatych wymienia się:",
 a:["bezgłośną pracę kół o zębach prostych",
    "bardzo niski koszt wykonania kół zębatych",
    "zupełny brak konieczności smarowania kół",
    "dużą sprawność (0,98–0,99) i zwartą budowę"],c:3,
 e:"Zalety: zwarta budowa, wysoka sprawność (0,98–0,99), niezawodność i trwałość."},
{t:"przek",q:"Istotną wadą przekładni zębatych o zębach prostych jest:",
 a:["mała sprawność przenoszenia mocy",
    "głośna praca przy współpracy zębów",
    "niemożność przenoszenia dużych mocy",
    "brak zwartości i duże gabaryty budowy"],c:1,
 e:"Wadą zębów prostych jest głośna praca; koszt wykonania kół jest również istotny."},
{t:"przek",q:"Główną zaletą zarysu ewolwentowego zęba jest:",
 a:["mała wrażliwość na odchyłki odległości osi kół",
    "całkowity brak nacisków stykowych Hertza",
    "zerowy koszt wykonania kół tym zarysem",
    "wyeliminowanie potrzeby stosowania korekcji"],c:0,
 e:"Zarys ewolwentowy daje stałe przełożenie nawet przy odchyłkach rozstawu osi."},
{t:"przek",q:"Wadą zazębienia zewnętrznego o zarysie ewolwentowym jest:",
 a:["niemożność doboru kół w dowolne pary",
    "całkowity brak ciągłości procesu zazębienia",
    "współpraca powierzchni wypukłych – duże naciski Hertza",
    "zbyt cicha praca poważnie utrudniająca słuchową kontrolę stanu kół"],c:2,
 e:"Przy zazębieniu zewnętrznym współpracują powierzchnie wypukłe → duże naciski stykowe Hertza."},
{t:"przek",q:"Podstawowe prawo zazębienia wymaga, aby wspólna normalna w punkcie styku zębów:",
 a:["była zawsze prostopadła do osi obu wałów",
    "przechodziła dokładnie przez wierzchołek współpracującego zęba",
    "była styczna do okręgu wierzchołkowego koła",
    "dzieliła odcinek O₁O₂ w stałym stosunku (przełożeniu)"],c:3,
 e:"Wspólna normalna musi dzielić odcinek między osiami w stałym stosunku równym przełożeniu."},
{t:"przek",q:"Graniczna liczba zębów koła walcowego (α = 20°, h*a = 1) wynosi teoretycznie:",
 a:["zg = 5, praktycznie około 4",
    "zg = 17, praktycznie około 14",
    "zg = 50, praktycznie około 45",
    "zg = 100, praktycznie około 90"],c:1,
 e:"Dla α = 20° teoretyczna graniczna liczba zębów to zg = 17 (praktycznie ok. 14)."},
{t:"przek",q:"Podcięcie podstawy zęba (podcięcie stopy) następuje, gdy liczba zębów:",
 a:["jest mniejsza od granicznej (z < zg)",
    "jest dokładnie równa granicznej (z = zg)",
    "jest większa od granicznej (z > zg)",
    "jest liczbą parzystą podzielną przez cztery"],c:0,
 e:"Podcięcie pojawia się przy z < zg – wierzchołek narzędzia podcina stopę zęba."},
{t:"przek",q:"Korekcję zarysu (przesunięcie x) stosuje się przede wszystkim, aby:",
 a:["uniknąć podcięcia zęba przy małej liczbie zębów",
    "zwiększyć masę i bezwładność koła zębatego",
    "zmienić barwę powierzchni roboczej zęba",
    "wyeliminować konieczność smarowania zazębienia"],c:0,
 e:"Korekcję stosuje się m.in. by uniknąć podcięcia przy z < zg oraz wyrównać wytrzymałość zębów."},
{t:"przek",q:"Korekcja zerowa (P-0) charakteryzuje się tym, że:",
 a:["x₁ = x₂, a odległość osi wyraźnie rośnie",
    "x₁ = −x₂, a odległość osi nie ulega zmianie",
    "stosuje się ją wyłącznie w przekładniach ślimakowych",
    "zawsze powoduje podcięcie podstawy zęba"],c:1,
 e:"W korekcji zerowej P-0 x₁ = −x₂, więc odległość osi pozostaje niezmieniona."},
{t:"przek",q:"Przekładnia stożkowa hipoidalna, w porównaniu ze stożkową czołową:",
 a:["ma sprawność dokładnie równą 100%",
    "w ogóle nie wykorzystuje zazębienia kół",
    "ma osie obu kół zawsze leżące na jednej wspólnej prostej geometrycznej",
    "ma przesuniętą oś zębnika – większą wytrzymałość i płynność"],c:3,
 e:"W przekładni hipoidalnej oś zębnika jest przesunięta, co daje większą wytrzymałość i płynność."},
{t:"przek",q:"Koło zębate współpracujące z zębatką prostą (listwą) służy do:",
 a:["zamiany ruchu obrotowego na postępowy i odwrotnie",
    "nieograniczonego zwiększania momentu skręcającego",
    "hamowania obracającego się bębna hamulcowego",
    "tłumienia drgań skrętnych w układzie napędowym"],c:0,
 e:"Para koło–zębatka zamienia ruch obrotowy na postępowy (i odwrotnie); listwa to koło o R = ∞."},
{t:"przek",q:"Średnicę podziałową koła zębatego określa zależność:",
 a:["d = m / z, jako iloraz modułu i liczby zębów",
    "d = z + m, jako suma liczby zębów i modułu",
    "d = z · m, jako iloczyn liczby zębów i modułu",
    "d = π / m, jako iloraz liczby π i modułu"],c:2,
 e:"Średnica podziałowa d = z·m (bo podziałka p = πm, a d = z·p/π)."},
];
