/* Baza pytań quizu PKM II — poziom egzaminacyjny (wersja trudna).
 * {t, q, a:[4], c:indeks poprawnej, e:wyjaśnienie, h:wskazówka}
 * Dystraktory są bliskie poprawnej; część pytań to "które stwierdzenie jest FAŁSZYWE".
 */
window.TOPICS = {
 gwint: {name:"Połączenia gwintowe", ico:"\uD83D\uDD29"},
 spaw:  {name:"Połączenia spawane",  ico:"\uD83D\uDD25"},
 sprz:  {name:"Sprzęgła",            ico:"\u2699\uFE0F"},
 ham:   {name:"Hamulce",             ico:"\uD83D\uDED1"},
 przek: {name:"Przekładnie zębate",  ico:"\uD83E\uDDB7"},
};

window.QUESTIONS = [
/* ===== POŁĄCZENIA GWINTOWE ===== */
{t:"gwint",q:"Które stwierdzenie o rozkładzie obciążenia na zwojach gwintu jest FAŁSZYWE?",
 a:["pierwszy zwój u nasady przenosi największą część obciążenia",
    "zwiększanie liczby zwojów proporcjonalnie odciąża pierwszy zwój",
    "rozkład jest nierównomierny wskutek odkształceń śruby i nakrętki",
    "wzór na wysokość nakrętki zakłada uproszczenie równomiernego nacisku"],c:1,
 e:"Dalsze zwoje przenoszą coraz mniej; dodawanie zwojów NIE odciąża proporcjonalnie pierwszego — stąd ograniczony sens bardzo wysokich nakrętek.",
 h:"Czy 20. zwój pracuje tak samo jak pierwszy?"},
{t:"gwint",q:"W jednoimiennych złączach spoczynkowych dopuszczalne naciski można powiększyć o:",
 a:["20% ÷ 50% względem wartości tablicowych",
    "5% ÷ 10% względem wartości tablicowych",
    "100% ÷ 150% względem wartości tablicowych",
    "wcale — tablicowe są wartościami nieprzekraczalnymi"],c:0,
 e:"Dla jednoimiennych złączy spoczynkowych naciski można zwiększyć o 20–50%.",
 h:"To kilkadziesiąt procent, nie kilka i nie kilkaset."},
{t:"gwint",q:"Współczynnik 1,13 we wzorze d_r = 1,13·√(Q/k_r) wynika bezpośrednio z:",
 a:["przyjętego zapasu bezpieczeństwa na rozciąganie",
    "wartości pierwiastka z 4/π przy zamianie pola koła",
    "empirycznego współczynnika spiętrzenia naprężeń",
    "stosunku średnicy rdzenia do średnicy nominalnej"],c:1,
 e:"Z σ_r = Q/(πd_r²/4): d_r = √(4Q/πk_r) = √(4/π)·√(Q/k_r) ≈ 1,13·√(Q/k_r).",
 h:"Skąd bierze się π w polu przekroju koła?"},
{t:"gwint",q:"W naprężeniu zastępczym śruby napędowej czynnik k_{r,c}/k_s przy τ uwzględnia:",
 a:["różną wartość dopuszczalną dla ściskania i rozciągania",
    "różną wrażliwość materiału na naprężenia normalne i styczne",
    "wpływ karbu gwintu na koncentrację naprężeń",
    "udział tarcia w gwincie w bilansie momentu"],c:1,
 e:"Współczynnik k_{r,c}/k_s sprowadza naprężenia styczne do normalnych zgodnie z przyjętą hipotezą wytrzymałościową.",
 h:"Po co przelicza się τ na „równoważne” σ?"},
{t:"gwint",q:"Dla smukłości λ = λ_gr wartości naprężenia krytycznego wg Eulera i Tetmajera:",
 a:["są sobie równe (krzywe stykają się w punkcie granicznym)",
    "różnią się o stały współczynnik bezpieczeństwa x_w",
    "Euler daje wartość wyższą niż Tetmajer",
    "Tetmajer daje wartość wyższą niż Euler"],c:0,
 e:"λ_gr to punkt zszycia obu zakresów — w nim σ_kr Eulera = σ_kr Tetmajera.",
 h:"Dlaczego akurat tam przełącza się wzory?"},
{t:"gwint",q:"Dla którego sposobu zamocowania śruby współczynnik μ_w = 0,7?",
 a:["jeden koniec utwierdzony, drugi swobodny (wspornik)",
    "oba końce połączone przegubowo (przegub–przegub)",
    "jeden koniec utwierdzony, drugi podparty przegubowo",
    "oba końce utwierdzone bez możliwości obrotu"],c:2,
 e:"Przypadki Eulera: wspornik μ_w=2; przegub–przegub μ_w=1; utwierdzenie–przegub μ_w=0,7; utwierdzenie–utwierdzenie μ_w=0,5.",
 h:"Wartość pośrednia między 1 a 0,5."},
{t:"gwint",q:"Minimalny promień bezwładności i_min = 0,25·d_r dla rdzenia śruby wynika z:",
 a:["założenia przekroju pierścieniowego rdzenia gwintu",
    "definicji i = √(I/A) dla przekroju kołowego",
    "empirycznej zależności dla stali konstrukcyjnych",
    "stosunku skoku gwintu do średnicy rdzenia"],c:1,
 e:"Dla koła i = √(I/A) = √((πd⁴/64)/(πd²/4)) = d/4 = 0,25·d_r.",
 h:"Policz I/A dla pełnego koła."},
{t:"gwint",q:"Kąt ugięcia śruby w przedziale 1°–2° klasyfikuje się jako:",
 a:["całkowicie bezpieczny, bez wpływu na trwałość",
    "niebezpieczny zwłaszcza przy obciążeniach zmęczeniowych",
    "dopuszczalny wyłącznie przy obciążeniach statycznych",
    "krytyczny, prowadzący do natychmiastowego zniszczenia"],c:1,
 e:"Do 0,5° — bezpieczny; 1–2° — niebezpieczny przy zmęczeniu; powyżej 3° — wysokie ryzyko uszkodzenia.",
 h:"To strefa pośrednia między bezpieczną a krytyczną."},
{t:"gwint",q:"Współczynnik obciążenia złącza χ (w Q = Q_w + χ·Q_p) zależy przede wszystkim od:",
 a:["wartości napięcia wstępnego Q_w nadanego przy montażu",
    "stosunku sztywności śruby do sztywności łączonych elementów",
    "współczynnika tarcia panującego w gwincie nakrętki",
    "liczby czynnych zwojów współpracującego gwintu"],c:1,
 e:"χ wynika z charakterystyk odkształceń: χ = C_s/(C_s + C_k) — im sztywniejsze kołnierze, tym mniejsze dociążenie śruby.",
 h:"Pomyśl, jak dzieli się siła między dwie sprężyny równoległe."},
{t:"gwint",q:"Wstępne napięcie połączenia śrubowego poprawia trwałość zmęczeniową, ponieważ:",
 a:["całkowicie eliminuje naprężenia w trzpieniu śruby",
    "śruba przejmuje tylko część χ·Q_p zmiennego obciążenia",
    "zwiększa średnicę rdzenia pracującego na rozciąganie",
    "obniża współczynnik tarcia między kołnierzami złącza"],c:1,
 e:"Przy napięciu wstępnym amplituda naprężeń w śrubie to tylko χ·Q_p (mała część obciążenia zewnętrznego), co wydłuża trwałość.",
 h:"Co realnie „dochodzi” do śruby, a co przejmują kołnierze?"},
{t:"gwint",q:"Sztywność śruby o zmiennym przekroju oblicza się ze wzoru:",
 a:["C_s = F_s·E_s / l_s, dla zastępczego pola stałego",
    "C_s = E_s / Σ(l_{si}/F_{si}), sumując podatności odcinków",
    "C_s = Σ(F_{si}·E_s) / l_s, sumując sztywności pól",
    "C_s = E_s·Σ F_{si} / Σ l_{si}, jako wartość średnia"],c:1,
 e:"Odcinki o różnym przekroju to sprężyny szeregowe — sumuje się podatności: C_s = E_s/Σ(l_{si}/F_{si}).",
 h:"Odcinki łączą się szeregowo, nie równolegle."},
{t:"gwint",q:"Naprężenie dopuszczalne dla obciążeń zmiennych względem statycznych charakteryzuje:",
 a:["k_{rj} = Z_rc/x_z, gdzie x_z = 2,5 ÷ 4,0",
    "k_{rj} = R_e/x_e, gdzie x_e = 1,3 ÷ 2,5",
    "k_{rj} = R_m/x_z, gdzie x_z = 1,0 ÷ 1,3",
    "k_{rj} = Z_rc·x_z, gdzie x_z = 0,5 ÷ 1,0"],c:0,
 e:"Dla zmiennych: k_{rj} = Z_rc/x_z, x_z = 2,5 ÷ 4,0 (większy zapas niż statyczne x_e = 1,3 ÷ 2,5).",
 h:"Obciążenia zmienne wymagają większego zapasu i wytrzymałości zmęczeniowej Z_rc."},
{t:"gwint",q:"Zabiegiem zmniejszającym ugięcie i naprężenia gnące śruby NIE jest:",
 a:["zastosowanie powierzchni lub podkładek kulistych pod łbem",
    "zwiększenie smukłości śruby przez zmniejszenie d_r",
    "zwiększenie średnicy rdzenia przy tej samej długości",
    "dokładne wykonanie równoległych powierzchni oporowych"],c:2,
 e:"Zwiększenie d_r zmniejsza smukłość, więc rośnie σ_g = ½(d_r/l)Eδ — to działa odwrotnie do celu.",
 h:"σ_g rośnie z d_r/l — co z nim robi grubszy rdzeń?"},
{t:"gwint",q:"Warunek wytrzymałości na naciski powierzchniowe, z którego liczy się wysokość nakrętki, to:",
 a:["σ_r = Q/(πd_r²/4) ≤ k_r dla rdzenia śruby",
    "p = Q/A_z ≤ p_dop, gdzie A_z = (π/4)(d²−D₁²)·i",
    "τ = M_s/W_o ≤ k_s dla przekroju gwintu",
    "σ_c ≤ σ_kr/x_w z warunku stateczności"],c:1,
 e:"Wysokość nakrętki dobiera się z p = Q/A_z ≤ p_dop, gdzie A_z = (π/4)(d²−D₁²)·i.",
 h:"Chodzi o docisk między zwojami, nie o rozciąganie rdzenia."},
{t:"gwint",q:"Hak dźwigowy i śruba podnośnikowa różnią się tym, że:",
 a:["hak jest tylko rozciągany, podnośnikowa rozciągana i skręcana",
    "hak jest rozciągany i skręcany, podnośnikowa tylko skręcana",
    "oba są obciążone identycznie siłą osiową i momentem",
    "hak jest ściskany, a podnośnikowa wyłącznie rozciągana"],c:0,
 e:"Hak — czyste rozciąganie osiowe; śruba podnośnikowa — rozciąganie + skręcanie (stan złożony).",
 h:"Która z nich „wkręca się” w obciążenie?"},
{t:"gwint",q:"Współczynnik bezpieczeństwa na wyboczenie x_w przyjmuje wartości znacznie większe niż przy zwykłym rozciąganiu, bo:",
 a:["materiał śruby ściskanej szybciej ulega zmęczeniu",
    "utrata stateczności jest nagła i wrażliwa na odchyłki osiowości",
    "naprężenia ściskające są zawsze wyższe od rozciągających dla danej śruby",
    "wzór Eulera systematycznie zaniża naprężenie krytyczne"],c:1,
 e:"x_w = 6 ÷ 8 — duży zapas, bo wyboczenie jest niestateczne i czułe na imperfekcje (mimośród, krzywizna).",
 h:"Dlaczego utrata stateczności jest groźniejsza niż płynięcie?"},

/* ===== POŁĄCZENIA SPAWANE ===== */
{t:"spaw",q:"Który rodzaj obciążenia spoiny ma NAJNIŻSZY współczynnik wytrzymałości statycznej z_o?",
 a:["rozciąganie, z_o = 0,75",
    "ściskanie, z_o = 0,80",
    "zginanie, z_o = 0,80",
    "ścinanie, z_o = 0,65"],c:3,
 e:"z_o: rozciąganie 0,75; ściskanie i zginanie 0,80; ścinanie 0,65 — najniższy dla ścinania.",
 h:"Spoina najsłabiej znosi naprężenia styczne."},
{t:"spaw",q:"W spoinie czołowej ścinanej współczynnik α wg PN-90/B-03200 wynosi:",
 a:["α_n = 1,0 oraz α_t = 0,6",
    "α_n = 0 oraz α_t = 0,6",
    "α_n = 0,8 oraz α_t = 0,7",
    "α_n = 0,6 oraz α_t = 0"],c:1,
 e:"Dla spoiny czołowej przy ścinaniu α_n = 0, α_t = 0,6; przy ściskaniu/zginaniu α_n = 1.",
 h:"Spoina czołowa „normalnie” nie pracuje na ścinanie — stąd zerowy współczynnik normalny."},
{t:"spaw",q:"Współczynnik α spoiny obniża się o 30%, gdy spoina jest jednocześnie:",
 a:["montażowa oraz pułapowa (oba przypadki łącznie)",
    "wyłącznie pułapowa, wykonywana nad głową",
    "wyłącznie montażowa, scalająca konstrukcję",
    "warsztatowa, lecz kontrolowana defektoskopowo"],c:0,
 e:"Obniżki: montażowe −10%, pułapowe −20%, oba przypadki naraz −30%.",
 h:"Dwie niekorzystne okoliczności sumują się."},
{t:"spaw",q:"Liczba „3” w warunku spoiny czołowej σ_z = √(σ_g² + 3τ²) ≤ k'_g pochodzi z:",
 a:["hipotezy wytrzymałościowej (energii odkształcenia postaciowego)",
    "potrojonego współczynnika bezpieczeństwa przyjmowanego dla ścinania spoiny",
    "liczby kierunków głównych w stanie naprężenia",
    "empirycznego współczynnika spiętrzenia w spoinie"],c:0,
 e:"Czynnik 3 przy τ² wynika z hipotezy Hubera–Misesa (naprężenie zredukowane).",
 h:"Ten sam „3” pojawia się w naprężeniu zredukowanym von Misesa."},
{t:"spaw",q:"Efektywna długość spoiny pachwinowej l_eff wg Eurokodu 3 to długość całkowita:",
 a:["pomniejszona o dwie efektywne grubości a (kratery końców)",
    "powiększona o dwie efektywne grubości a na zakończeniach",
    "pomniejszona o połowę grubości łączonego elementu",
    "równa całkowitej, bez żadnych potrąceń końcówek"],c:0,
 e:"l_eff to długość o pełnym przetopie — od całkowitej odejmuje się 2a (niepełny przetop na początku i końcu).",
 h:"Początek i koniec ściegu nie mają pełnego przetopu."},
{t:"spaw",q:"Wymóg a ≤ 0,7·t_min dla spoiny pachwinowej (maksimum skurczowe) ma na celu:",
 a:["zapewnienie stabilności łuku spawalniczego",
    "ochronę przed nadmiernymi naprężeniami skurczowymi",
    "ograniczenie masy naniesionego stopiwa",
    "zapobieganie zbyt szybkiemu chłodzeniu spoiny"],c:1,
 e:"Zbyt gruba spoina względem cienkiego elementu daje duże naprężenia skurczowe — stąd a ≤ 0,7·t_min.",
 h:"Co dzieje się, gdy gruba spoina stygnie na cienkiej blasze?"},
{t:"spaw",q:"Warunek a ≥ √(t_max) − 0,5 mm (masa termiczna) zapobiega:",
 a:["zbyt szybkiemu chłodzeniu i kruchości spoiny",
    "nadmiernym naprężeniom skurczowym w złączu",
    "niestabilności łuku przy małej grubości",
    "podtopieniom brzegów grubego elementu"],c:0,
 e:"Przy grubym elemencie cienka spoina stygnie zbyt szybko (odprowadzenie ciepła) — rośnie kruchość; stąd dolny limit a.",
 h:"Gruby element to duży „radiator” odbierający ciepło."},
{t:"spaw",q:"Zasadnicza różnica między ujęciem Eurokodu 3 a PN-90/B-03200 polega na tym, że:",
 a:["Eurokod 3 — metoda stanów granicznych; PN — naprężeń dopuszczalnych",
    "Eurokod 3 — naprężeń dopuszczalnych; PN-90/B-03200 — stanów granicznych",
    "obie normy używają wyłącznie metody stanów granicznych",
    "obie normy używają wyłącznie naprężeń dopuszczalnych"],c:0,
 e:"Eurokod 3 bazuje na stanach granicznych, a starsze ujęcie PN na naprężeniach dopuszczalnych.",
 h:"Nowoczesne normy operują „stanami granicznymi”."},
{t:"spaw",q:"Które stwierdzenie o spoinach jest FAŁSZYWE?",
 a:["spoiny czołowe łączą elementy dosunięte czołami",
    "spoiny pachwinowe mają przekrój trójkąta równoramiennego",
    "spoiny otworowe łączą elementy dosunięte czołami przez rowek",
    "kształt rowka spoiny czołowej przypomina litery I, V, X, U"],c:2,
 e:"Spoiny otworowe łączą elementy NASUNIĘTE na siebie — przez otwory wypełniane spoiną, nie czołami.",
 h:"Otwory robi się w elementach leżących jeden na drugim."},
{t:"spaw",q:"Współczynnik jakości spoiny z = 1,0 można przyjąć, gdy:",
 a:["spoina jest poddana defektoskopii na całej długości",
    "spoina wykonywana jest w pozycji pułapowej",
    "stosuje się najtańszą technologię spawania ręcznego",
    "łączone elementy są wykonane z żeliwa szarego"],c:0,
 e:"Pełna kontrola/defektoskopia spoiny pozwala przyjąć najwyższą jakość (z bliskie 1,0; α_n = 1).",
 h:"Najwyższa jakość = pełna kontrola wad."},
{t:"spaw",q:"Sprężysto-plastyczny stan odkształceń w spoinie jest dopuszczalny:",
 a:["zawsze, niezależnie od charakteru obciążenia",
    "przy obciążeniach statycznych, lecz nie przy zmęczeniowych",
    "tylko przy obciążeniach zmęczeniowych zmiennych",
    "wyłącznie w spoinach czołowych wykonanych z pełnym przetopem grani"],c:1,
 e:"Statycznie mała deformacja plastyczna nie zagraża funkcjonalności; przy zmęczeniu znacznie obniża trwałość.",
 h:"Statyka „wybacza”, zmęczenie nie."},
{t:"spaw",q:"Grubość obliczeniową a spoiny pachwinowej mierzy się jako:",
 a:["wysokość trójkąta, prostopadle do jego zewnętrznego boku",
    "długość jednego z przyprostokątnych boków trójkąta",
    "przeponę trójkąta wzdłuż lica spoiny",
    "odległość między brzegami obu łączonych elementów"],c:0,
 e:"a to wysokość największego wpisanego trójkąta, mierzona prostopadle do zewnętrznego boku (lica).",
 h:"To najkrótszy wymiar od „korzenia” do lica."},
{t:"spaw",q:"Naprężenie dopuszczalne w spoinie wg PN-90/B-03200 ma postać:",
 a:["k' = α·R_e/x_e, gdzie α to wsp. wytrzymałości spoiny",
    "k' = z_o·z·k_r, jak w metodzie naprężeń dopuszczalnych",
    "k' = R_m·α/z, odniesione do wytrzymałości doraźnej",
    "k' = α + R_e − x_e, jako kombinacja liniowa"],c:0,
 e:"Wg PN-90/B-03200 (stany graniczne) k' = α·k = α·R_e/x_e.",
 h:"To metoda stanów granicznych, więc bazuje na R_e i x_e."},
{t:"spaw",q:"Element złącza spawanego o najbardziej zmienionej strukturze (zagrożony pęknięciami) to:",
 a:["lico spoiny od strony zewnętrznej",
    "strefa wpływu ciepła (SWC) obok spoiny",
    "grań spoiny po stronie przetopu",
    "materiał rodzimy z dala od złącza"],c:1,
 e:"SWC to obszar materiału rodzimego o zmienionej strukturze (przegrzanie/zahartowanie) — często krytyczny.",
 h:"Nie sama spoina, lecz materiał tuż obok niej."},

/* ===== SPRZĘGŁA ===== */
{t:"sprz",q:"W którym typie sprzęgieł współczynnik przeciążenia K ma składowe w MIANOWNIKU?",
 a:["w sprzęgłach sztywnych: K = K₁ + K₂",
    "w sprzęgłach zębatych: K = K₁·K₂·K₃",
    "w sprzęgłach ciernych: K = K₁/(K₂·K₃)",
    "w sprzęgłach Cardana: K = 1,33·K₁·K₂·K₃"],c:2,
 e:"Tylko dla ciernych K = K₁/(K₂·K₃) — K₂ (poślizg) i K₃ (liczba włączeń) są w mianowniku.",
 h:"Który typ przenosi moment tarciem i „toleruje” poślizg?"},
{t:"sprz",q:"Mnożnik 1,33 w K = 1,33·K₁·K₂·K₃ dla sprzęgieł Cardana uwzględnia:",
 a:["niejednostajność pracy pojedynczego przegubu",
    "stały zapas bezpieczeństwa na ścinanie krzyżaka",
    "wpływ temperatury pracy na elementy przegubu",
    "liczbę przegubów w połączeniu szeregowym"],c:0,
 e:"Współczynnik 1,33 ujmuje dodatkowe, dynamiczne obciążenie od niejednostajnego biegu przegubu Cardana.",
 h:"Co jest „wadą” pojedynczego przegubu Cardana?"},
{t:"sprz",q:"Dobór sprzęgła podatnego wg DIN 740-2 sprowadza się do warunku:",
 a:["M_znam ≥ M_max, przy K = S_A·S_Z·S_t",
    "M_znam ≤ M_max, przy K = S_A + S_Z + S_t",
    "M_T ≥ K·M, przy K = S_A/(S_Z·S_t)",
    "M_znam = M_max, przy K = S_A·S_Z/S_t"],c:0,
 e:"Wg DIN 740-2 K = S_A·S_Z·S_t, a dobór sprawdza M_znam ≥ M_max = K·M.",
 h:"Moment znamionowy katalogowy musi „pokryć” maksymalny."},
{t:"sprz",q:"W doborze wg DIN 740-2 współczynniki S_A, S_Z, S_t odpowiadają kolejno:",
 a:["uderzeniom, częstości rozruchów, temperaturze pracy",
    "temperaturze, uderzeniom, częstości rozruchów",
    "rozruchom, temperaturze pracy, uderzeniom udaru",
    "sztywności, podatności, tłumieniu drgań skrętnych"],c:0,
 e:"S_A — uderzeń (charakterystyka napędu/maszyny), S_Z — częstości rozruchów, S_t — temperatury pracy.",
 h:"Litera „t” sugeruje temperaturę."},
{t:"sprz",q:"Sprzęgło podatne dobiera się tak, by n = T/τ ≥ 12 ÷ 20, ponieważ:",
 a:["zapewnia to maksymalny współczynnik przenoszenia impulsu",
    "praca przy n bliskim 1 oznaczałaby rezonans drgań skrętnych",
    "powyżej 20 sprzęgło traci zdolność tłumienia",
    "dla n < 12 moment obrotowy nie jest przenoszony"],c:1,
 e:"Przy n→1 układ pracowałby w rezonansie; dobór n_gr = 12÷20 odsuwa pracę daleko od strefy rezonansu.",
 h:"Co dzieje się, gdy częstość wymuszenia ≈ własna?"},
{t:"sprz",q:"Sprzęgło ze śrubami pasowanymi LUŹNO przenosi moment obrotowy przez:",
 a:["siłę tarcia między dociśniętymi tarczami kołnierzy",
    "siłę ścinającą działającą na trzpienie śrub",
    "docisk czołowych kłów obu połówek sprzęgła",
    "pole elektromagnetyczne wzbudzane w tarczach"],c:0,
 e:"Śruby luźne → moment przez tarcie tarcz (śruby napinają); śruby pasowane ciasno → moment przez ich ścinanie.",
 h:"Luźna śruba nie dotyka ścianki otworu — co więc trzyma?"},
{t:"sprz",q:"Sprzęgło krzyżakowe (Oldhama) służy przede wszystkim do kompensacji niewspółosiowości:",
 a:["promieniowej (równoległe przesunięcie osi wałów)",
    "kątowej (znaczne, zamierzone załamanie osi wałów pod kątem)",
    "osiowej (wzdłużne przesunięcie wałów)",
    "wyłącznie skrętnej (drgania momentu)"],c:0,
 e:"Sprzęgło Oldhama (krzyżakowe) kompensuje głównie przesunięcie promieniowe osi wałów.",
 h:"Tarcza pośrednia ślizga się w dwóch prostopadłych rowkach."},
{t:"sprz",q:"Które stwierdzenie o sprzęgłach jest FAŁSZYWE?",
 a:["sprzęgła sztywne wymagają zachowania współosiowości wałów",
    "sprzęgła podatne tłumią drgania skrętne dzięki wkładce",
    "sprzęgła samonastawne służą do zamierzonej zmiany kąta osi",
    "pojedynczy przegub Cardana daje niejednostajny bieg"],c:2,
 e:"Zamierzoną zmianę kąta osi realizują sprzęgła PRZEGUBOWE (Cardana), a nie samonastawne (te kompensują drobne błędy).",
 h:"Nie myl „samonastawnych” z „przegubowymi”."},
{t:"sprz",q:"Sprzęgło bezpieczeństwa wielopłytkowe ogranicza moment dzięki temu, że:",
 a:["płytki dociskane są sprężynami, a po przeciążeniu ślizgają się",
    "kły wchodzą w zazębienie dopiero po pełnej synchronizacji prędkości",
    "siła odśrodkowa rozłącza je przy wysokich obrotach",
    "blokuje obrót w jednym kierunku jak zapadka"],c:0,
 e:"Docisk płytek (regulowany nakrętkami) ustala moment graniczny; po przeciążeniu następuje poślizg i spadek momentu.",
 h:"To sprzęgło cierne z nastawnym dociskiem."},
{t:"sprz",q:"W sprzęgle ciernym włączalnym kontrola nacisków przyjmuje postać:",
 a:["p = 2M/(D_śr·z·A) ≤ p_dop",
    "p = M·D_śr/(z·A) ≤ p_dop",
    "p = 2M·z·A/D_śr ≤ p_dop",
    "p = z·A/(2M·D_śr) ≤ p_dop"],c:0,
 e:"Kontrola nacisków: p = 2M/(D_śr·z·A) ≤ p_dop (z — liczba elementów, A — pole styku).",
 h:"Moment „rozkłada się” na średnicę, liczbę i pole styku."},
{t:"sprz",q:"Sprzęgło odśrodkowe załącza się, gdy:",
 a:["moment przekroczy wartość graniczną nastawioną sprężyną",
    "prędkość obrotowa wzrośnie na tyle, że siły odśrodkowe docisną elementy",
    "kierunek obrotów wału czynnego ulegnie odwróceniu",
    "temperatura elastycznej wkładki spadnie poniżej ustalonej wartości progowej"],c:1,
 e:"Sprzęgło odśrodkowe załącza się samoczynnie przy odpowiednio wysokich obrotach (siły odśrodkowe).",
 h:"Działa „od obrotów”, nie od momentu."},
{t:"sprz",q:"Sprzęgła rozłączne sterowane włączane synchronicznie to wyłącznie sprzęgła:",
 a:["kłowe oraz zębate (kształtowe)",
    "tarczowe oraz wielopłytkowe cierne",
    "stożkowe cierne oraz bezpieczeństwa",
    "odśrodkowe oraz jednokierunkowe"],c:0,
 e:"Synchronicznie (kształtowo) włącza się sprzęgła kłowe i zębate; cierne (tarczowe, wielopłytkowe, stożkowe) — asynchronicznie.",
 h:"Synchroniczne = kształtowe, bez poślizgu."},
{t:"sprz",q:"Sprzęgło sztywne przy braku współosiowości wałów powoduje przede wszystkim:",
 a:["tłumienie powstałych drgań skrętnych układu",
    "dodatkowe przeciążenie wałów i łożysk",
    "samoczynną kompensację błędu ustawienia",
    "obniżenie przenoszonego momentu obrotowego"],c:1,
 e:"Sprzęgło sztywne nie kompensuje błędów — niewspółosiowość daje dodatkowe siły obciążające wały i łożyska.",
 h:"Sztywne połączenie „przenosi” błąd dalej."},
{t:"sprz",q:"Współczynnik przeciążenia dla sprzęgieł jednokierunkowych ma postać:",
 a:["K = (K₁ + K₂)·K₃, gdzie K₃ zależy od kształtu profilu gwiazdy",
    "K = K₁·K₂·K₃, gdzie K₃ zależy od czasu pracy",
    "K = K₁/(K₂·K₃), gdzie K₃ zależy od poślizgu",
    "K = 1,33·K₁·K₂, ze stałym mnożnikiem dynamicznym przegubu Cardana"],c:0,
 e:"Dla sprzęgieł jednokierunkowych K = (K₁ + K₂)·K₃, gdzie K₃ zależy od kształtu profilu gwiazdy.",
 h:"Łączy sumę (jak sztywne) z dodatkowym czynnikiem profilu."},
{t:"sprz",q:"Nominalny moment sprzęgła M = 9550·N/n wymaga podstawienia jednostek:",
 a:["N w kW oraz n w obr/min",
    "N w W oraz n w rad/s",
    "N w kW oraz n w rad/s",
    "N w KM oraz n w obr/s"],c:0,
 e:"Wzór praktyczny M = 9550·N/n obowiązuje dla N [kW] i n [obr/min]; podstawowy to M = N/ω (N [W], ω [rad/s]).",
 h:"Stała 9550 „ukrywa” przeliczenie obr/min i kW."},

/* ===== HAMULCE ===== */
{t:"ham",q:"W pojedynczym hamulcu klockowym z dźwignią podpartą w A₁ siła P zależy od kierunku obrotów, bo:",
 a:["moment tarcia T·c raz pomaga, a raz przeszkadza w dociskaniu klocka",
    "siła normalna N całkowicie zmienia znak przy zmianie kierunku obrotu bębna",
    "promień bębna R zależy od kierunku jego obracania",
    "współczynnik tarcia μ rośnie tylko w jednym kierunku"],c:0,
 e:"Z sumy momentów względem A₁: P = M_T/(μR)·(b∓μc)/a — moment od T (ramię c) raz odejmuje, raz dodaje.",
 h:"To człon z μc raz ma znak minus, raz plus."},
{t:"ham",q:"Aby siła P w hamulcu klockowym była niezależna od kierunku obrotów, należy:",
 a:["przenieść podparcie dźwigni do punktu A₂ na linii działania N",
    "maksymalnie zwiększyć ramię c względem ramienia b",
    "zmniejszyć współczynnik tarcia μ do wartości bliskiej zeru",
    "zastosować dwa klocki dociskane niezależnymi sprężynami"],c:0,
 e:"Podparcie w A₂ (na osi N) eliminuje człon z μc: P = M_T/(μR)·(b/a) — niezależne od kierunku.",
 h:"Trzeba „zlikwidować” ramię momentu tarcia."},
{t:"ham",q:"Hamulec klockowy działa jak samohamowna zapadka, gdy:",
 a:["b < μc (ramię b mniejsze od iloczynu μc)",
    "b > μc (ramię b większe od iloczynu μc)",
    "a = b (ramiona dźwigni równe sobie)",
    "μ = 0 (tarcie praktycznie zanika)"],c:0,
 e:"Przy b < μc siła P_A1 staje się ujemna — klocek zaciska się samoczynnie (zapadka).",
 h:"To „odwrócenie znaku” w warunku b∓μc."},
{t:"ham",q:"W szczękowym hamulcu bębnowym w układzie symetrycznym:",
 a:["siły N₁ i N₂ są nierówne (szczęka nabiegająca i zbiegająca)",
    "siły N₁ i N₂ są zawsze dokładnie równe sobie",
    "obie szczęki są całkowicie odciążone podczas hamowania",
    "działanie szczęk nie zależy od kierunku obrotu bębna"],c:0,
 e:"W układzie symetrycznym N₁/N₂ = (e₂−μe₃)/(e₂+μe₃) ≠ 1 — jedna szczęka nabiega, druga zbiega.",
 h:"Jedna szczęka „pomaga” sobie tarciem, druga nie."},
{t:"ham",q:"Moment hamujący hamulca taśmowego można zapisać jako:",
 a:["M_H = (S₁ − S₂)·D_H/2 = (e^{μα} − 1)·S₂·D_H/2",
    "M_H = (S₁ + S₂)·D_H/2 = (e^{μα} + 1)·S₂·D_H/2",
    "M_H = (S₁ − S₂)·D_H = (e^{μα} − 1)·S₂·D_H",
    "M_H = (S₁·S₂)·D_H/2, jako iloczyn naciągów"],c:0,
 e:"M_H = (S₁ − S₂)·D_H/2, a po podstawieniu S₁ = S₂·e^{μα} daje (e^{μα} − 1)·S₂·D_H/2.",
 h:"To różnica naciągów razy promień bębna."},
{t:"ham",q:"Hamulec taśmowy różnicowy działa jak zapadka (samohamowny), gdy:",
 a:["a₂ ≤ a₁·e^{μα} (ramię a₂ dostatecznie małe)",
    "a₂ ≥ a₁·e^{μα} (ramię a₂ dostatecznie duże)",
    "a₁ = a₂ (oba ramiona jednakowe)",
    "α = 0 (zerowy kąt opasania bębna)"],c:0,
 e:"Dla G = (S₂a₂ − S₁a₁)/l, gdy a₂ ≤ a₁·e^{μα}, siła G przestaje być dodatnia → samohamowność.",
 h:"Porównaj iloczyny ramion z wykładniczym S₁/S₂."},
{t:"ham",q:"Które przyporządkowanie hamulca taśmowego do wzoru na siłę G jest FAŁSZYWE?",
 a:["zwykły: G = S₂·a/l (jeden kierunek pracy)",
    "sumowy: G = (S₁ + S₂)·a/l (dwa kierunki pracy)",
    "różnicowy: G = (S₂·a₂ − S₁·a₁)/l (jeden kierunek)",
    "zwykły: G = (S₁ + S₂)·a/l (dwa kierunki pracy)"],c:3,
 e:"Hamulec zwykły to G = S₂·a/l (jeden kierunek); wzór (S₁+S₂)a/l dotyczy hamulca SUMOWEGO.",
 h:"Zwykły ≠ sumowy — sprawdź, gdzie jest suma naciągów."},
{t:"ham",q:"Przy projektowaniu hamulca przyjmuje się moment tarcia M_T względem M_o jako:",
 a:["(1,75 ÷ 2,5)·M_o, z zapasem na pewne zahamowanie",
    "(0,3 ÷ 0,5)·M_o, jako ułamek momentu obrotowego",
    "(5 ÷ 8)·M_o, z bardzo dużym zapasem bezpieczeństwa",
    "dokładnie 1·M_o, bez jakiegokolwiek zapasu"],c:0,
 e:"Zakłada się M_T = (1,75 ÷ 2,5)·M_o — zapas gwarantuje pewne zahamowanie.",
 h:"Trochę ponad dwukrotność, nie ułamek i nie wielokrotność."},
{t:"ham",q:"Hamulec różni się od sprzęgła ciernego przede wszystkim tym, że:",
 a:["jeden z jego członów połączony jest z elementem nieruchomym",
    "nie wykorzystuje w ogóle zjawiska tarcia współpracujących powierzchni",
    "przenosi wyłącznie moment obrotowy między wałami",
    "działa jedynie przy stałej, niezmiennej prędkości"],c:0,
 e:"W hamulcu jeden człon jest nieruchomy (zatrzymuje ruch), w sprzęgle oba mogą się obracać.",
 h:"Co w hamulcu „stoi w miejscu”?"},
{t:"ham",q:"Nacisk jednostkowy między taśmą a bębnem hamulca taśmowego wynosi:",
 a:["p = 2S/(b₀·D_H), gdzie b₀ to szerokość taśmy",
    "p = S·D_H/(2·b₀), proporcjonalnie do średnicy",
    "p = b₀·D_H/(2S), odwrotnie do naciągu",
    "p = S·b₀/(2·D_H), jako iloczyn przez średnicę"],c:0,
 e:"Nacisk jednostkowy p = 2S/(b₀·D_H) (b₀ — szerokość taśmy, D_H — średnica bębna).",
 h:"Im szerszy bęben i taśma, tym mniejszy nacisk."},
{t:"ham",q:"Które stwierdzenie o zastosowaniu hamulców jest FAŁSZYWE?",
 a:["klockowe stosuje się w dźwignicach i kolejkach górskich",
    "szczękowe bębnowe stosuje się powszechnie w pojazdach",
    "taśmowe są głównymi hamulcami roboczymi precyzyjnych obrabiarek",
    "taśmowe pełnią najczęściej rolę hamulców pomocniczych i postojowych"],c:2,
 e:"Hamulce taśmowe to głównie hamulce pomocnicze/postojowe, a NIE główne robocze precyzyjnych obrabiarek.",
 h:"Dwa zdania o taśmowych są sprzeczne — które?"},
{t:"ham",q:"Założenie M_T > M_o w hamulcu oznacza, że moment tarcia musi:",
 a:["przewyższać moment obracający, by ruch został zatrzymany",
    "być równy momentowi obracającemu dla ruchu jednostajnego",
    "być mniejszy od obracającego, by uniknąć przegrzania",
    "zależeć wyłącznie od średnicy bębna hamulcowego"],c:0,
 e:"Aby zahamować, moment tarcia musi przewyższać moment napędzający (M_T > M_o), stąd zapas 1,75–2,5.",
 h:"Żeby zatrzymać, trzeba „przeważyć” napęd."},

/* ===== PRZEKŁADNIE ZĘBATE ===== */
{t:"przek",q:"Które przyporządkowanie przełożeń jest FAŁSZYWE?",
 a:["kinematyczne: i = ω₁/ω₂ = n₁/n₂",
    "geometryczne: u = d₂/d₁ = z₂/z₁",
    "dynamiczne: u·η = M₂/M₁",
    "kinematyczne: i = z₂/z₁ = d₂/d₁"],c:3,
 e:"Kinematyczne dotyczy PRĘDKOŚCI (ω, n); stosunek liczby zębów/średnic to przełożenie GEOMETRYCZNE.",
 h:"Nie myl prędkości z liczbą zębów."},
{t:"przek",q:"Reduktor i multiplikator różnią się tym, że:",
 a:["reduktor i > 1, czynny zębnik; multiplikator i < 1, czynne koło",
    "reduktor i < 1, czynne koło; multiplikator i > 1, czynny zębnik",
    "oba mają i > 1, lecz różny kierunek obrotów wału",
    "oba mają i < 1, lecz różną liczbę stopni przekładni"],c:0,
 e:"Reduktor (i>1) zwalnia i zwiększa moment — czynny jest mały zębnik; multiplikator (i<1) przyspiesza — czynne koło.",
 h:"Co napędza, gdy chcemy zwolnić obroty?"},
{t:"przek",q:"Sprawność przekładni stożkowej hipoidalnej w porównaniu z czołową:",
 a:["jest nieco niższa (≈96% vs ≈99%) mimo lepszej płynności",
    "jest wyższa i osiąga praktycznie 100%",
    "jest identyczna, bo geometria zazębienia jest taka sama",
    "nie ma znaczenia, bo obie pracują bez strat"],c:0,
 e:"Hipoidalna ma większą wytrzymałość i płynność, ale przez poślizg wzdłużny niższą sprawność (≈96% vs ≈99%).",
 h:"Lepsza płynność „kosztuje” trochę sprawności."},
{t:"przek",q:"Graniczna liczba zębów z_g zależy od kąta zarysu α tak, że dla α = 15° wynosi:",
 a:["z_g = 30 (praktycznie 25), więcej niż dla α = 20°",
    "z_g = 17 (praktycznie 14), tyle samo co dla α = 20°",
    "z_g = 10 (praktycznie 8), mniej niż dla α = 20°",
    "z_g = 50 (praktycznie 45), niezależnie od kąta"],c:0,
 e:"z_g = 2h*_a/sin²α: mniejszy kąt α → większe z_g; dla 15° z_g=30 (25), dla 20° z_g=17 (14).",
 h:"Mniejszy kąt zarysu = większa skłonność do podcięcia."},
{t:"przek",q:"Funkcja ewolwentowa kąta przyjmuje postać:",
 a:["inv α = tg α − α (kąt α w radianach)",
    "inv α = α − tg α (kąt α w radianach)",
    "inv α = sin α − α (kąt α w radianach)",
    "inv α = tg α + α (kąt α w radianach)"],c:0,
 e:"inv α = tg α − α — podstawowa zależność opisująca zarys ewolwentowy.",
 h:"Tangens minus sam kąt."},
{t:"przek",q:"Podstawowe prawo zazębienia wymaga, by wspólna normalna w punkcie styku:",
 a:["dzieliła odcinek O₁O₂ w stałym stosunku r_{w2}/r_{w1}",
    "była zawsze prostopadła do linii łączącej osie kół",
    "przechodziła przez wierzchołek aktualnie zazębionego zęba",
    "pokrywała się ze styczną do okręgów wierzchołkowych"],c:0,
 e:"Dla stałego przełożenia normalna N–N musi dzielić O₁O₂ w stałym stosunku równym przełożeniu (punkt C).",
 h:"Stały punkt podziału = stałe przełożenie."},
{t:"przek",q:"Które stwierdzenie o zarysie ewolwentowym jest FAŁSZYWE?",
 a:["jest mało wrażliwy na odchyłki odległości osi kół",
    "koła o tym samym module i kącie można kojarzyć w pary",
    "przy zazębieniu zewnętrznym daje małe naciski stykowe",
    "można go nacinać jednym narzędziem metodą obwiedniową"],c:2,
 e:"Wadą zazębienia zewnętrznego ewolwentowego są DUŻE naciski Hertza (styk dwóch powierzchni wypukłych).",
 h:"Wypukła do wypukłej — mały czy duży styk?"},
{t:"przek",q:"Wskaźnik zazębienia ε pary kół powinien spełniać warunek:",
 a:["ε > 1, aby zachowana była ciągłość zazębienia",
    "ε = 0, aby zęby stykały się tylko w jednym punkcie",
    "ε < 1, aby zmniejszyć naciski stykowe zębów",
    "ε = π, niezależnie od liczby zębów kół"],c:0,
 e:"ε = ε₁ + ε₂ > 1 zapewnia, że zanim jedna para zębów wyjdzie z przyporu, druga już w nim jest.",
 h:"Zawsze musi być w styku co najmniej jedna para zębów."},
{t:"przek",q:"Przy korekcji zarysu współczynnikiem x > 0 grubość zęba s = (π/2 + 2x·tgα)·m:",
 a:["rośnie u podstawy, lecz nadmierne x grozi zaostrzeniem wierzchołka",
    "maleje u podstawy i jednocześnie rozszerza wierzchołek",
    "pozostaje dokładnie stała niezależnie od przyjętej wartości współczynnika x",
    "rośnie tylko wtedy, gdy jednocześnie maleje moduł m"],c:0,
 e:"x>0 pogrubia ząb u podstawy (wzmocnienie), ale przy zbyt dużym x wierzchołek może ulec zaostrzeniu.",
 h:"Coś zyskujemy u dołu, ale czym ryzykujemy u góry?"},
{t:"przek",q:"Korekcja zerowa (P-0) charakteryzuje się tym, że:",
 a:["x₁ = −x₂, więc odległość osi pozostaje niezmieniona",
    "x₁ = x₂ > 0, więc odległość osi wyraźnie wzrasta",
    "x₁ = x₂ = 0 zawsze, więc korekcja w ogóle nie działa",
    "stosuje się ją tylko w przekładniach ślimakowych"],c:0,
 e:"W P-0 x₁ = −x₂ (suma zero) — odległość osi bez zmian; warunek: z₁ + z₂ ≥ 2z_g.",
 h:"Suma przesunięć równa zeru."},
{t:"przek",q:"Linia zęba strzałkowa (daszkowa), w odróżnieniu od skośnej, charakteryzuje się tym, że:",
 a:["znosi wzajemnie siły osiowe od obu połówek uzębienia",
    "generuje większą wypadkową siłę osiową na łożyskach",
    "całkowicie eliminuje płynność współpracy zębów",
    "może być nacinana wyłącznie metodą kształtową"],c:0,
 e:"Ząb strzałkowy to dwa skośne o przeciwnych pochyleniach — ich siły osiowe znoszą się (brak obciążenia osiowego łożysk).",
 h:"Dwa „daszki” pochylone przeciwnie — co z siłami wzdłuż osi?"},
{t:"przek",q:"Średnica zasadnicza i podziałowa koła powiązane są zależnością:",
 a:["d_b = d·cosα, a ogólnie d = d_b/cos(α_Y)",
    "d_b = d·sinα, a ogólnie d = d_b·cos(α_Y)",
    "d_b = d/cosα, a ogólnie d = d_b·sin(α_Y)",
    "d_b = d·tgα, a ogólnie d = d_b/tg(α_Y)"],c:0,
 e:"d_b = d·cosα; dla dowolnego okręgu d = d_b/cos(α_Y).",
 h:"To zależność z cosinusem kąta zarysu."},
{t:"przek",q:"Ogólna sprawność układu napędowego oraz przełożenie całkowite wyrażają się jako:",
 a:["η = η₁·η₂·η₃ oraz u = u₁·u₂·…·uₓ (iloczyny)",
    "η = η₁+η₂+η₃ oraz u = u₁+u₂+…+uₓ (sumy)",
    "η = η₁·η₂·η₃ oraz u = u₁+u₂+…+uₓ (mieszane)",
    "η = η₁+η₂+η₃ oraz u = u₁·u₂·…·uₓ (mieszane)"],c:0,
 e:"Zarówno sprawności, jak i przełożenia stopni MNOŻĄ się: η = Πηᵢ, u = Πuᵢ.",
 h:"Oba to iloczyny, nie sumy."},
{t:"przek",q:"Para koło–zębatka prosta (listwa) realizuje zamianę ruchu, ponieważ listwa to:",
 a:["koło zębate o promieniu dążącym do nieskończoności",
    "koło o zerowej liczbie zębów i zerowym module",
    "element cierny bez właściwego uzębienia",
    "przekładnia cięgnowa o nieskończonym przełożeniu"],c:0,
 e:"Listwę traktuje się jako koło o promieniu R→∞, dzięki czemu zamienia ruch obrotowy na postępowy.",
 h:"Co się dzieje z kołem, gdy jego promień rośnie do nieskończoności?"},
];
